site_name: "Qiulin's Homepage"
site_url: "https://qiulinfan.github.io"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top   # 把导航移到顶部
    - navigation.tabs  # 顶部标签形式（可选）
  custom_dir: overrides

nav:
    - Projects:
        - Game Projects: https://qiulinfan.github.io/games/index.html
    - EECS notes:
        - C++ Programming: https://qiulinfan.github.io/cpp-notes/index.html
        - Data Structures and Algorithms: https://qiulinfan.github.io/dsa/index.html
        - Machine Learning & Deep Learning: https://qiulinfan.github.io/ml/index.html
        - Computer Vision: https://qiulinfan.github.io/cv/index.html
        - NLP: https://qiulinfan.github.io/nlp/index.html
        - Unity Game Dev: https://qiulinfan.github.io/unity/index.html
    - Math notes:
        - Measure Theory: https://qiulinfan.github.io/measure/index.html