site_name: "Qiulin's Homepage"
site_url: "https://SaddySamoyed.github.io/"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Home: index.md
  - EECS Subjects:
      - C++ Programming: notes/cpp/index.md
      - Data Structures and Algorithms: notes/dsa/index.md
      - Machine Learning & Deep Learning: notes/ml/index.md
      - Nonlinear Optimization: notes/opt/index.md
      - Computer Vision: notes/cv/index.md
      - NLP: notes/nlp/index.md
      - Computer Graphics: notes/graphics/index.md
      - Unity & Game Development: notes/unity/index.md
  - Math Subjects:
      - Multivariate Analysis: notes/analysis/index.md
      - Matrix Theory: notes/linear-algebra/index.md
      - Basic Topology: notes/topology/index.md
      - Measure Theory: notes/measure/index.md
