#import "../../toolchain/qlnotes.typ": *
#import "../../toolchain/math-aliases.typ": *

= sigma-algebra 与 measure
<sigma-algebra-与-measure>
== $sigma$-algebra \[Fol 1.2\]
<sigma-algebra-fol-1.2>
我们 (见 my Math 395 notes) 已经证明: 在 $bb(R)$ 上不存在一个 measure function $mu : cal(P)\(bb(R)\)arrow.r\[0\,oo\]$ satisfying:

+ $mu\(nothing\)= 0$\;

+ translate invariant

+ countably additivite

因而, 对于比如 $bb(R)$ 的这种无法在其幂集上定义良好的 measure function 的集合, 我们要定义一个 $cal(A) subset.eq cal(P)\(X\)$, 使得我们能在这个 power set 的子集上, 定义一个 make sense 的 measure. \ \ 首先, 为了对于一个任意的集合 $X$ 都能在其上定义 measure, 我们要考虑在 $X$ 的一个什么样的子集簇上有希望定义这样的 measure.

#definition(
  title: [algera, $sigma$-algebra],
  id: "def-01-sigma-algebra-measure-algera-sigma-algebra",
  concepts: ("algera-sigma-algebra",),
  depends: (),
  aliases: ("algera, \\sigma-algebra",),
)[
对于 set $X$, $S subset.eq cal(P)\(X\)$ 被称为 $X$ 上的一个 $sigma$-algebra, if 其满足:

+ $nothing in X$\;

+ #strong[closed under complement]: if $E in S$ then $X\\E in S$\;

+ #strong[closed under countable union]: if $E_1\,E_2\,dots.h.c in S$ then $union.big_(k = 1)^oo E_k in S$.

如果第三条并不满足, 而是只满足 #strong[closed under finite union], 则称 $S$ 是 $X$ 上的一个 algebra. 当然, $sigma$-algebra 是比 algebra 严格更强的条件.

]
我们定义 $X$ 的一个子集簇为一个 $sigma$-algebra 如果它包含空集并 closed under complement and countable union. 但这并不是 $sigma$-algebra 的全部性质. 这三个性质还蕴涵了: $sigma$-algebra 也一定包含 $X$, 且 #strong[closed under set difference], #strong[symmetric difference] 以及 #strong[countable intersection]. \ #strong[对于 algebra, 它也有以上的所有性质的 finite version.]

#theorem(
  title: [$sigma$-algebra also closed under set difference, symmetric difference
and countable intersection],
  id: "thm-01-sigma-algebra-measure-sigma-algebra-also-closed-under-set-difference-symmetric-differe",
  concepts: ("sigma-algebra-also-closed-under-set-difference-symmetric-differe",),
  depends: (),
  aliases: ("\\sigma-algebra also closed under set difference, symmetric difference and countable intersection",),
)[
Let $S$ be a $sigma$-algebra on set $X$. \ Claim:

+ $X in S$

  #proof[
  Directly from def.

  ]

+ $D\,E in S arrow.r.double.long D union E\,D inter E\,D\\E in S$

  #proof[
  union: from def by leaving others as $nothing$\; \ intersection: $ \(D inter E\)^C= D^C union E^C in S $
  setminus: $ D\\E = D inter\(X\\E\)in S $

  ]

+ $D\,E in S arrow.r.double.long D Delta S in S$

  #proof[
  $ D Delta E =\(D\\E\)union.big\(E\\D\) $

  ]

+ $A_1\,A_2\,dots.h.c in S arrow.r.double.long inter.big_(i = 1)^oo A_i in S$

  #proof[
  $ \(inter.big_(n = 1)^oo\)^C= union.big_(n = 1)^oo E_n^C in S $

  ]

]
#remark[
我们发现 $sigma$-algerbra 很像是 topology. 实际上 $sigma$-algerbra 和 topology 的区别就是: $sigma$-algebra 只保证了 closed under countable union 而 topology closed under any union; topology 只保证 closed under finite intersection 而 $sigma$-algebra closed under countable intersection.

]
#lemma(
  title: [任意 $sigma$-algebra 的 intersection 仍是 $sigma$-algebra],
  id: "lem-01-sigma-algebra-measure-sigma-algebra-intersection-sigma-algebra",
  concepts: ("sigma-algebra-intersection-sigma-algebra",),
  depends: (),
  aliases: ("任意 \\sigma-algebra 的 intersection 仍是 \\sigma-algebra",),
)[
Let ${ S_alpha }_(alpha in A)$ be a collection of $sigma$-algebra on $X$, then $inter.big_(alpha in A) S_alpha$ is a $sigma$-algebra on $X$.

]
#proof[
这是个 trivial proof. 但是它具有一定理解上的启发. \ 我们对 $sigma$-algebra 有一个直观理解: 如果我们想把一些集合做成一个 $sigma$-algebra, 那么首先我们把它们的补集放进这个 $sigma$-algebra 里, 其次我们把这些集合的 up to countable 的任意组合的并集也放进这个 $sigma$-algebra 里. \ 因而即便我们把一些 $sigma$-algebra 给 intersect 起来, 其中每个集合的补集和这些集合的 up to ctbl 的任意组合的并集也在这个 intersection 里. \ 这是个重要的直观理解. 我们想到, 如果我们要把一个 sigma-algebra 里的一部分去掉，并保持它仍然是一个 sigma-algebra，那么我们得把这些集合的补集, 以及能够 ctbly union 成这些集合的小集合也去掉, 并对这些小集合也 recursively 进行这个操作.

]
#corollary(
  title: [unique smallest $sigma$-algebra containing a collection of subsets],
  id: "cor-01-sigma-algebra-measure-unique-smallest-sigma-algebra-containing-a-collection-of-subsets",
  concepts: ("unique-smallest-sigma-algebra-containing-a-collection-of-subsets",),
  depends: (),
  aliases: ("unique smallest \\sigma-algebra containing a collection of subsets",),
)[
Given $epsilon subset.eq cal(P)\(X\)$
$ < epsilon > := inter.big_(epsilon subset.eq S subset.eq cal(P)\(X\)\,thin S upright(" is ") sigma upright(" -algebra on ") X) S $

]
#definition(
  title: [$sigma$-algebra generated by a subset],
  id: "def-01-sigma-algebra-measure-sigma-algebra-generated-by-a-subset",
  concepts: ("sigma-algebra-generated-by-a-subset",),
  depends: (),
  aliases: ("\\sigma-algebra generated by a subset",),
)[
We call $ < epsilon > := inter.big_(epsilon subset.eq S subset.eq cal(P)\(X\)\,thin S upright(" is ") sigma upright(" -algebra on ") X) S $ #strong[the $sigma$-algebra generated by $epsilon$]

]
== Borel $sigma$-algebra on $bb(R)$ and measure \[Fol 1.2, finished; 1.3\]
<borel-sigma-algebra-on-mathbbr-and-measure-fol-1.2-finished-1.3>
Recall: the $sigma$-algebra generated by $epsilon$
$ < epsilon > := inter.big_(epsilon subset.eq S subset.eq cal(P)\(X\)\,thin S upright(" is ") sigma upright(" -algebra on ") X) S $ is the smallsest $sigma$-algebra containing $epsilon$.

#example(
  id: "ex-01-sigma-algebra-measure-example-001",
  concepts: ("example-001",),
  depends: (),
)[
$ < { E } > = { nothing\,E\,E^c\,X } $

]
#lemma(
  title: [inclusion properties of generated $sigma$-algebra],
  id: "lem-01-sigma-algebra-measure-inclusion-properties-of-generated-sigma-algebra",
  concepts: ("inclusion-properties-of-generated-sigma-algebra",),
  depends: (),
  aliases: ("inclusion properties of generated \\sigma-algebra",),
)[
+ if $cal(E) subset.eq cal(A)$ where $cal(A)$ is a $sigma$-algebra, then $< cal(E) > subset.eq cal(A)$.

+ if $cal(E) subset.eq cal(F)$, then $< cal(E) > subset.eq < cal(F) >$.

+ if $cal(E) subset.eq < cal(F) >$, then $< cal(E) > subset.eq < cal(F) >$.

]
#proof[
trivial.

]
#definition(
  title: [Borel $sigma$-algebra defined on a topological space],
  id: "def-01-sigma-algebra-measure-borel-sigma-algebra-defined-on-a-topological-space",
  concepts: ("borel-sigma-algebra-defined-on-a-topological-space",),
  depends: (),
  aliases: ("Borel \\sigma-algebra defined on a topological space",),
)[
For topological space $\(X\,cal(T)\)$, we define:
$ cal(B)_X := < cal(T) > $

]
#strong[Borel $sigma$-algebra] on a topological space 就是 $sigma$-algebra generated by the topology. Its members are called #strong[Borel sets]. 当然, 所有的 open sets 和 closed sets 都是 Borel sets.

=== generating Borel $sigma$-algebra on $bb(R)$
<generating-borel-sigma-algebra-on-mathbbr>
#example(
  id: "ex-01-sigma-algebra-measure-example-002",
  concepts: ("example-002",),
  depends: (),
)[
Let
$cal(E)_1$: $bb(R)$ 上所有的 open intervals; \ $cal(E)_2$: $bb(R)$ 上所有的 closed intervals; \ $cal(E)_3$: $bb(R)$ 上所有的左开右闭 intervals; \ $cal(E)_4$: $bb(R)$ 上所有的左闭右开 intervals; \ $cal(E)_5$: $bb(R)$ 上所有的左开右无界 intervals; \ $cal(E)_6$: $bb(R)$ 上所有的左闭右无界 intervals; \ $cal(E)_7$: $bb(R)$ 上所有的左无界右开 intervals; \ $cal(E)_8$: $bb(R)$ 上所有的左无界右闭 intervals; \ $union.big_(i = 1\,dots.h.c\,8) cal(E)_i$ 即 $bb(R)$ 上的所有形式的 interals.

#lemma(
  id: "lem-01-sigma-algebra-measure-lemma-003",
  concepts: ("lemma-003",),
  depends: (),
)[
任意以上 $cal(E)_i\,i = 1\,dots.h.c\,8$ 都可以 generate $cal(B)_(bb(R))$

]
]
#proof[
我们 recall: 所有的 countable 以及 second countable 的 topological space 都具有 #strong[Lindelöf property]: 任意 open covering 都存在一个 countable 的 subcovering. \ Lindelöf property 的一个推论就是, 在具有 Lindelöf property 的 metric space 或者 second countable 的 space 中, 任意 open set 都可以写成 countable 个 open balls 的 union. \ 我们在 elementary 的 real analysis 中已经学过, $\[a\,b\)= inter_(n gt.eq 1)\(a - 1\/n\,b\)$, 以其作为例子, 这些 intervals 彼此之间都可以相互转换.

]

=== measure
<measure>
#definition(
  title: [measurable space and measure space],
  id: "def-01-sigma-algebra-measure-measurable-space-and-measure-space",
  concepts: ("measurable-space-and-measure-space",),
  depends: (),
  aliases: ("measurable space and measure space",),
)[
Let $X$ be a set, $cal(M)$ be a $sigma$-algebra on $X$. \ A measure on $\(X\,A\)$ is a function $mu : cal(M) arrow.r\[0\,oo\)$ satisfying:

+ $mu\(nothing\)= 0$

+ countable additive:
  $ mu\(union.big_(i = 1)^oo E_i\)= sum_(i = 1)^oo mu\(E_i\) $ for disjoint seq of $E_i in cal(M)$.

如果这样的 $mu$ 存在, 我们则称 $\(X\,cal(M)\)$ 为一个 measurable space, 并称 $\(X\,cal(M)\,mu\)$ 为一个 measure space.

]
#remark[
一个 probability space 就是一个 measure space, satisfying $mu\(X\)= 1$.

]
#example(
  id: "ex-01-sigma-algebra-measure-example-003",
  concepts: ("example-003",),
  depends: (),
)[
+ 对于任意的 $\(X\,cal(M)\)$, 我们可以定义:
  $ mu\(A\):=\#A #h(0em) #h(0em) #h(0em)\(in bb(Z)_(gt.eq 0) union { oo }\) $
  这个 measure 叫做 #strong[counting measure].

+ Fix $x_0 in M$, 可以 define
  $ mu\(A\):= delta_x := {1 #h(0em) upright(", if ") x_0 in A\
  0 #h(0em) upright(", if ") x_0 in.not A\
   $
  这个 measure 叫做 the #strong[Dirac measure at $x_0$].

+ 给定一个 $X$ 上的函数 $f : X arrow.r\[0\,oo\)$, 我们可以通过这个函数来定义:
  $ mu\(A\):= sum_(x in A) f\(x\) $
  这个测度依赖于函数值来表示每个点的单点集的 measure, 并通过一个集合上所有点的单点集 measure 相加得到这个集合在这个函数下的 measure. (缺点: 我们已经知道, 如果一个函数在一个集合上的正集是 uncountable 的, 那么这个集合上的这个测度一定是 $oo$\.)

]
以下是 measure function 由它的定义的两条性质(空集为0以及 ctbl additivity)推导出的一些基本性质:

#lemma(
  title: [measure is finitely additive],
  id: "lem-01-sigma-algebra-measure-measure-is-finitely-additive",
  concepts: ("measure-is-finitely-additive",),
  depends: (),
  aliases: ("measure is finitely additive",),
)[
Measure is finitely additive.

]
#proof[
显然, ctbl additive implies finite additive.

]
#remark[
反向则不成立. 这让我们想起: Jordan measure 和 Lebesgue measure.

]
#lemma(
  id: "lem-01-sigma-algebra-measure-lemma-005",
  concepts: ("lemma-005",),
  depends: (),
)[
$A\,B in cal(M) arrow.r.double.long$
$ mu\(A\)+ mu\(B\)= mu\(A inter B\)+ mu\(A union B\) $

]
#proof[
$ A union B =\(A\\B\)union.sq\(A inter B\)union.sq\(B\\A\) $
而后使用 finite additive 可得. 这是一个 direct corollary of countable additivity.

]
#corollary(
  id: "cor-01-sigma-algebra-measure-corollary-002",
  concepts: ("corollary-002",),
  depends: (),
)[
$A\,B in cal(M)\,A subset.eq B\,mu\(A\)< oo arrow.r.double.long$
$ mu\(B\\A\)= mu\(B\)- mu\(A\) $

]
#theorem(
  title: [properties of measure],
  id: "thm-01-sigma-algebra-measure-properties-of-measure",
  concepts: ("properties-of-measure",),
  depends: (),
  aliases: ("properties of measure",),
)[
对于任何 measure space $\(X\,cal(M)\,mu\)$:

+ #strong[monotonicity]: $A subset.eq B in cal(M) arrow.r.double.long mu\(A\)lt.eq thin mu\(B\)$

  #proof[
  trivial.

  ]

+ #strong[countable subadditivity]:
  $ mu\(union.big_(i = 1)^oo A_i\)lt.eq sum_(i = 1)^oo mu\(A_i\) $

  #proof[
  By setting $B_i = A_i\\ union.big_(j = 1)^(i - 1) A_j$, 而后通过 ctbl disjoint additivity 与 monotonicity 可得

  ]

+ #strong[continuous from above]:
  如果 $A_i subset.eq A_(i + 1) forall i gt.eq 2 arrow.r.double.long$
  $ mu\(union.big_(i = 1)^oo A_i\)= lim_(i arrow.r oo) mu\(A_i\) $

  #proof[
  使用 same trick as 2.

  ]

+ #strong[countinuous from below]:
  如果 $A_i supset.eq A_(i + 1) forall i$ 且存在某个 $j$ 使得 $mu\(A_i\)< oo$, 则
  $ mu\(inter.big_(i = 1)^oo A_i\)= lim_(n arrow.r oo) mu\(A_n\) $

  #proof[
  前面的都无视, 直到第一个 measure $< oo$ 的集合, 是可能出现在最后的 intersection 里的最大集合. 我们 Fix 这个 $A_j$. 通过构造补集的方式, 把交转为并, 从而用 (3) 得证.
  Define:
  $E_i := A_j\\A_i forall i gt.eq j$
  从而
  $ union.big_(i = j)^oo E_i = A_j\\\(inter.big_(i = j)^oo A_i\) $进而
  $ mu\(union.big_(i = j)^oo E_i\)= mu\(A_j\)- mu\(inter.big_(i = j)^oo A_i\) $
  进而 by (3)
  $ mu\(inter.big_(i = 1)^oo A_i\)= mu\(inter.big_(i = j)^oo A_i\)= mu\(A_j\)- lim_(i arrow.r oo) mu\(E_i\)= mu\(A_j\)- lim_(i arrow.r oo)\(mu\(A_j\)- mu\(A_i\)\)= lim_(i arrow.r oo) A_i $

  ]

]
Recall: the $sigma$-algebra generated by $epsilon$
$ < epsilon > := inter.big_(epsilon subset.eq S subset.eq cal(P)\(X\)\,thin S upright(" is ") sigma upright(" -algebra on ") X) S $ is the smallsest $sigma$-algebra containing $epsilon$.

以下是 measure function 由它的定义的两条性质(空集为0以及 ctbl additivity)推导出的一些基本性质:

#lemma(
  title: [measure is finitely additive],
  id: "lem-01-sigma-algebra-measure-measure-is-finitely-additive-2",
  concepts: ("measure-is-finitely-additive",),
  depends: (),
  aliases: ("measure is finitely additive",),
)[
Measure is finitely additive.

]
#proof[
显然, ctbl additive implies finite additive.

]
#remark[
反向则不成立. 这让我们想起: Jordan measure 和 Lebesgue measure.

]
#lemma(
  id: "lem-01-sigma-algebra-measure-lemma-007",
  concepts: ("lemma-007",),
  depends: (),
)[
$A\,B in cal(M) arrow.r.double.long$
$ mu\(A\)+ mu\(B\)= mu\(A inter B\)+ mu\(A union B\) $

]
#proof[
$ A union B =\(A\\B\)union.sq\(A inter B\)union.sq\(B\\A\) $
而后使用 finite additive 可得. 这是一个 direct corollary of countable additivity.

]
#corollary(
  id: "cor-01-sigma-algebra-measure-corollary-003",
  concepts: ("corollary-003",),
  depends: (),
)[
$A\,B in cal(M)\,A subset.eq B\,mu\(A\)< oo arrow.r.double.long$
$ mu\(B\\A\)= mu\(B\)- mu\(A\) $

]
#theorem(
  title: [properties of measure],
  id: "thm-01-sigma-algebra-measure-properties-of-measure-2",
  concepts: ("properties-of-measure",),
  depends: (),
  aliases: ("properties of measure",),
)[
对于任何 measure space $\(X\,cal(M)\,mu\)$:

+ #strong[monotonicity]: $A subset.eq B in cal(M) arrow.r.double.long mu\(A\)lt.eq thin mu\(B\)$

  #proof[
  trivial.

  ]

+ #strong[countable subadditivity]:
  $ mu\(union.big_(i = 1)^oo A_i\)lt.eq sum_(i = 1)^oo mu\(A_i\) $

  #proof[
  By setting $B_i = A_i\\ union.big_(j = 1)^(i - 1) A_j$, 而后通过 ctbl disjoint additivity 与 monotonicity 可得

  ]

+ #strong[continuous from above]:
  如果 $A_i subset.eq A_(i + 1) forall i gt.eq 2 arrow.r.double.long$
  $ mu\(union.big_(i = 1)^oo A_i\)= lim_(i arrow.r oo) mu\(A_i\) $

  #proof[
  使用 same trick as 2.

  ]

+ #strong[countinuous from below]:
  如果 $A_i supset.eq A_(i + 1) forall i$ 且存在某个 $j$ 使得 $mu\(A_i\)< oo$, 则
  $ mu\(inter.big_(i = 1)^oo A_i\)= lim_(n arrow.r oo) mu\(A_n\) $

  #proof[
  前面的都无视, 直到第一个 measure $< oo$ 的集合, 是可能出现在最后的 intersection 里的最大集合. 我们 Fix 这个 $A_j$. 通过构造补集的方式, 把交转为并, 从而用 (3) 得证.
  Define:
  $E_i := A_j\\A_i forall i gt.eq j$
  从而
  $ union.big_(i = j)^oo E_i = A_j\\\(inter.big_(i = j)^oo A_i\) $进而
  $ mu\(union.big_(i = j)^oo E_i\)= mu\(A_j\)- mu\(inter.big_(i = j)^oo A_i\) $
  进而 by (3)
  $ mu\(inter.big_(i = 1)^oo A_i\)= mu\(inter.big_(i = j)^oo A_i\)= mu\(A_j\)- lim_(i arrow.r oo) mu\(E_i\)= mu\(A_j\)- lim_(i arrow.r oo)\(mu\(A_j\)- mu\(A_i\)\)= lim_(i arrow.r oo) A_i $

  ]

]
