#import "../../toolchain/qlnotes.typ": *
#import "../../toolchain/math-aliases.typ": *

= product measure and Fubini-Tonelli theorem
<product-measure-and-fubini-tonelli-theorem>
== product space and product measure \[Fol 1.2, finished; 2.5\]
<product-space-and-product-measure-fol-1.2-finished-2.5>
Goal: Given $\(X_i\,cal(A)_i\,mu_i\)$, construct $X = product X_i$, s.t.
$ mu\(E_1 times E_2\)= mu_1\(E_1\)mu_2\(E_2\) $
So that we can do Fubini (iterated integration) like that in Riemann integral.

=== product $sigma$-algebra
<product-sigma-algebra>
#definition(
  title: [#kn[product $sigma$-algebra]],
)[
Suppose $\(X_i\,cal(A)_i\)$ mble, $1 lt.eq i lt.eq n$, the product $sigma$-algebra $A_1 times.o dots.h.c times.o A_n$ on $X_1 times dots.h.c times X_n$ is the smallest #ref[sigma-algebra] s.t. the #strong[coordinate map] $ pi_j : X_1 times dots.h.c times X_n arrow.r X_j $#strong[is measurable.] \ 即 the $sigma$-algebra generated by: ${ pi_alpha\(E_alpha\): E_alpha in cal(A_alpha) }$. $ A_1 times.o dots.h.c times.o A_n : = < { pi_alpha\(E_alpha\): E_alpha in cal(A_alpha) } > $

]
我们容易发现:

#proposition(
)[
$ A_1 times.o dots.h.c times.o A_n = < { E_1 times dots.h.c times E_n in cal(A)_i times dots.h.c times cal(A)_n } > $

]
#proof[
By def 易得. (Prop 1.14 in book). \

]
#remark[
这里只考虑了有限情况, 但是无限的乃至于 ctblly 无限的相似. 取所有可能的 set product 作为 geneating 即可.

]
=== product Borel algebra $subset$ Borel algebra of the product space
<product-borel-algebra-subset-borel-algebra-of-the-product-space>
#proposition(
)[
If $X_1\,dots.h.c\,X_n$ are metric spaces. Let $X := X_1 times dots.h.c times X_n$ (with product metric), then: $ times.o.big_(i = 1)^n cal(B)_(X_i) subset.eq cal(B)_X $
#strong[and the equality holds if $X_i$ separable $forall i$.]

]
#proof[
$ times.o.big_(i = 1)^n cal(B)_(X_i) =^(upright("by prop")) < { U_1 times dots.h.c times U_n upright(" each open") } > subset.eq cal(B)_X $
Now let $C_i subset.eq X_i$ dense, ctbl. \ Set $ cal(E)_i := { B_r\(x\)divides x in C_i #h(0em)\,#h(0em) r in bb(Q)_(> 0) } subset.eq cal(B)_(X_i) $
Then: #strong[every open set in $X_1 times dots.h.c times X_n$ is a ctbl union of products $B_1 times dots.h.c times B_n$], each $B_1 in cal(E)_i$.
Then we have: $ B_X = < { B_1 times . . . times B_n } > subset times.o.big_1^n B_(X_i) $

]
#remark[
显然. #strong[有限 index] 情况下, 在 product topology 中, #strong[product of open sets仍然是 open set], 但是 open sets 可以不止是 product of open sets 这些. 因而 $times.o.big_(i = 1)^n cal(B)_(X_i) subset.eq cal(B)_X$. \ 并且在 separable 的 topological space 上, 比如 $bb(R)$, 我们有: $bb(R)^n$ 中的任意 open set 都是 a ctbl union of open boxes. 于是 $times.o.big_(i = 1)^n cal(B)_(bb(R)) = cal(B)_(bb(R)^n)$

]
#example(
)[
$ cal(B)_(bb(R)^n) = cal(B)_(bb(R)) times.o dots.h.c times.o cal(B)_(bb(R)) $

]
#corollary(
)[
if $\(X\,cal(A)\)$ is a mble space, then $ f : X arrow.r bb(C) #h(0em) #h(0em)\(cal(A)\,cal(B)_(bb(C))\)upright("-mble ") arrow.l.r.double Re f\,Im f #h(0em) #h(0em) cal(A) upright("-mble") $

]
#proof[
略.

]
=== construction of product measure
<construction-of-product-measure>
下面我们构建 product measure:
Let $\(X_i thin\,cal(A)_i thin\,mu_i\)$, $1 lt.eq i lt.eq n$ be mble spaces. \ And let $X := X_1 times . . . times X_n$, $cal(A) := cal(A)_i times.o dots.h.c times.o cal(A)_n$
Goal: 通过 Hahn-Kromolgrov 来构建 product measure on product mble space.
Idea: Let $ cal(A)' := { upright("all finite disjoint unions of rectangles (each measurable)") A_1 times dots.h.c times A_n } $
#strong[Step 1:]

=== all finite disjoint unions of rectangles as an algebra
<all-finite-disjoint-unions-of-rectangles-as-an-algebra>
#proposition(
)[
$cal(A)'$ is an algebra.

]
#proof[
The set $cal(E) := { upright("rectangles") } subset.eq cal(P)\(X\)$ satisfies:

- $diameter in cal(E)$

- $E\,F in cal(E) arrow.r.double.long E inter F in cal(E)$

- $E in cal(E) arrow.r.double.long E^c upright(" is a finite disjoint union of recs")$ (画图可知). \ \

]
#strong[Step 2:]

=== 各维度 measure 的 product 作为 rectangle 的 measure, 从而定义 premeasure
<各维度-measure-的-product-作为-rectangle-的-measure-从而定义-premeasure>
Now define $ mu' : cal(A)' arrow.r\[0\,oo\] $ as follows: $ mu'\(union.sq.big_(k = 1)^N E_1^(\(k\)) times dots.h.c times E_n^(\(k\))\)= sum_(k = 1)^N product_(i = 1)^n mu_i\(E_i^(\(k\))\) $
Claim 2:

#proposition(
)[
#strong[\(1) $mu'$ is a well-defined premeasure on $cal(A)'$. \ (2) If each $mu_i$ is $sigma$-finite, so is $mu'$.]

]
#proof[
Sketch: (2) DIY.
(1) STS(check): if $E = E_1 times dots.h.c E_n$ is a finite or ctbl union of rects $E^(\(k\)) = E_1^(\(k\)) times dots.h.c times E_n^(\(k\))$, then $ product_1^n mu_i\(E_i\)= sum_k product_1^n mu_i\(E_i^(\(k\))\) $
Use Tonelli for sums and integrals: $ product_1^n chi_(E_i)\(x_i\) & = chi_E\(x_1 thin\,dots.h.c thin\,x_n\)\
 & = sum_k chi_(E^(\(k\)))\(x_1 thin\,dots.h.c thin\,x_n\)\
 & = sum_k product_1^n chi_(E_i^(\(k\)))\(x_i\) $
Integrate w.r.t. $x_1$:
$ mu_1\(E_1\)product_(i = 1)^n chi_(E_i)\(x_i\) & = integral sum_k product_1^n chi_(E_i^(\(k\)))\(x_i\)\
 & =^(upright("Tonelli")) sum_k integral\(product_1^n chi_(E_i^(\(k\)))\(x_i\)\)d thin mu_1\(x_1\)\
 & = sum_k mu_1\(E_1^(\(k\))\)product_(i = 1)^n chi_(E_i^(\(k\)))\(x_i\) $
And repeat for $i = 2\,dots.h.c\,n$. \ \

]
=== HK extension of the premeasure as definition of product measure
<hk-extension-of-the-premeasure-as-definition-of-product-measure>
#strong[Step 3: 现在已经有了 $sigma$-finite 的 premeasure, 我们可以应用 HK Thm 构建出完整的 measure.]
Now use HK:

#corollary(
)[
$exists$ measure $mu := mu_1 times dots.h.c times mu_n$ on $cal(A) = cal(A)_1 times.o dots.h.c cal(A)_n$ extending $mu'$. \ (#strong[And if each $mu_i$ are $sigma$-finite, then product measure 也 $sigma$-finite, 从而 $mu$ 是 unique extension.)]

]
由此, 我们从 $cal(A)_1\,dots.h.c\,cal(A)_n$ 的 measure 中构建出了它们的 product measure. \ \

=== associativity of product $sigma$-algebra and $sigma$-finite product measure
<associativity-of-product-sigma-algebra-and-sigma-finite-product-measure>
#corollary(
  title: [#kn[associativity of product measure]],
)[
总有 $ cal(A)_1 times.o cal(A)_2 times.o cal(A)_3 =\(cal(A)_1 times.o cal(A)_2\)times.o cal(A)_3 = cal(A)_1 times.o\(cal(A)_2 times.o cal(A)_3\) $ 并且, if $mu_1\,mu_2\,mu_3$ are $sigma$-finite, then: $ mu_1 times mu_2 times mu_3 =\(mu_1 times mu_2\)times mu_3 = mu_1 times\(mu_2 times mu_3\) $

]
#proof[
DIY. 前者 play with def, 后者直接由 $sigma$-finite 的 premeasure 的 HK extension unique 得到.

]
=== 如何证明一个函数 product measurable
<如何证明一个函数-product-measurable>
要证明一个函数是 product measurable 的, 只需要证明它对于每个 measurable rectangle 的 preimage 都是 measurable 的即可.

#lemma(
)[
Suppose $f : X arrow.r Y times Z$ is a function from a measurable space $\(X\,cal(A)\)$ to a product measure space $\(Y times Z\,cal(B)_1 times.o cal(B)_2\)$. \ Claim: If $f^(- 1)\(B_1 times B_2\)in cal(A)$ for each measurable rectangle $B_1 times B_2 in cal(B)_1 times.o cal(B)_2$, then $f$ is an $\(cal(A)\,cal(B)_1 times.o cal(B)_2\)$-measurable function.

]
#proof[
因为 product $sigma$-algebra 由所有的 measurable rectangles 生成. \ Hw7 中有另一版的证明作为 lemma.

]
在 Hw7 中我们可以通过这个 lemma 得到一个结论: 如果 $E in cal(A times.o A)$, 那么 $E$ 的 diagonal 一定 $in cal(A)$.

对于特殊的函数, 比如两个 measurable function 的乘积, 其一定是 product measurable 的.

#lemma(
  title: [#kn[easier Fubini]],
)[
条件: $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$ 为 arbitrary measure space (不需要 $sigma$-finite.), $f : X arrow.r bb(C)$, $g : Y arrow.r bb(C)$ 为 measurable functions. \ 结论: $ h := f g quad upright("is ")\(cal(A) times.o cal(B)\)upright("-measurable") $
并且如果 $f\,g$ 是 $L^1$ 的, 那么 $h in L^1\(mu times nu\)$ 并且 $ integral h #h(0em) d\(mu times nu\)= \( integral f #h(0em) d mu \) \( integral g #h(0em) d nu \) $

]
#proof[
in hw 8. 这个 statement 表示一个 $cal(A) upright("-measurable")$ 的函数和一个 $cal(B) upright("-measurable")$ 的函数的乘积是 $\(cal(A) times.o cal(B)\)upright("-measurable")$ 的.

]
== Tonelli's Thm \[Fol 2.5\]
<tonellis-thm-fol-2.5>
我们将 focus on the case $n = 2$: $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$, 考虑 $ \(X times Y\,cal(A) times.o cal(B)\,mu times nu\) $
从而, 它可以推广到任何 finite 个 measure space 的 product 上.

=== $E subset X times Y$ 的 section
<esubset-x-times-y-的-section>
#definition(
  title: [#kn[$x$-section, $y$-section]],
)[
给定 product space 上的集合 $E subset X times Y$, 对于 $x in X$, $y in Y$, 我们定义:
$ E_x : = { y in Y divides\(x\,y\)in E } $
$ E^y := { x in X divides\(x\,y\)in Y } $

#figure(image("../assets/ch2-pics-image-20250220190452148.png", width: 30.0%),
  caption: [
  ]
)

给定从 product space 出发的函数 $f : X times Y arrow.r bb(C)$, 对于 $x in X$, $y in Y$, 我们定义: $ f_x\(y\):= f^y\(x\):= f\(x\,y\) $
表示固定住一个变量, 另一个变量的变化.

]
#example(
)[
对于任意的 $E subset X times Y$如果定义: $ f := chi_E $
那么有: $ f_x = chi_(E_x)\,quad f^y = chi_(E^y) $
对于 #strong[rectangle:] $E = A times B$, $A in cal(A)\,B in cal(B)$, 有 $ E_x = {diameter\,quad x in.not A\
B\,quad x in A $

]
#proposition(
)[
\(a) $ E in cal(A) times.o cal(B) arrow.r.double.long {E_x in cal(B)\,quad forall x in X\
E^y in cal(A) quad\,forall y in Y $ (b) $ f upright(" is ") cal(A) times.o cal(B) upright("-measurable") arrow.r.double.long {f_x upright(" is ") cal(B) upright("-measurable") #h(0em) #h(0em) forall x\
f^y upright(" is ") cal(A) upright("-measurable") #h(0em) #h(0em) forall y $

]
#proof[
\(a) Let $ cal(E) := { E subset X times Y divides E_x in cal(B) #h(0em) #h(0em) forall x in X quad upright(" and ") quad E^y in cal(A) #h(0em) #h(0em) forall y in Y } $
Claim: $cal(E)$ 包含了所有的 rectangles, 并且 $cal(E)$ a $sigma$-algebra. \ 容易证明这一点. 从而, 由 $cal(A) times.o cal(B)$ 的定义 (为包含所有 rectangles 的最小 $sigma$-algebra) 得 $cal(A) times.o cal(B) subset cal(E)$, 从而 (a) 成立 \ 并且由于 (check) $f_x^(- 1)\(V\)=\(f^(- 1)\(V\)\)_x$ (Similar for $f_y$), (a)$arrow.r.double.long$\(b).

]
#remark[
这里三件需要记住的事情:

- #strong[section 和取 preimage 可以交换顺序]

- 对于一个 product measurable set, 任意 #strong[section 也 measurable]

- 对于一个 product measurable function, 任意 #strong[section function 也 measurable]

]
#remark[
记录一下这里的证明方法, 以前见的比较少. 这里#strong[证明条件 A 推出条件 B] 的方法: #strong[证明所有满足条件 B 的元素构成的集合 包含了 所有满足条件 A 得元素构成的集合.] \ 这一方法的好处在于: 可以运用所有满足条件 B 的元素构成的集合的整体性质, 比如是 $sigma$-algebra 等.

]
#definition(
  title: [#kn[monotone class]],
)[
Given a set $X$, a collection $C subset cal(P)\(X\)$ is called a monotone class, if it is closed under #strong[countable increasing unions] and #strong[countable decreasing intersections]

]
当然, 一个 $sigma$-algebra 是一个 monotone class. monotone class 是一个比 $sigma$-algebra 更弱的定义.

=== tool needed to show Tonelli: Monotone Class Lemma
<tool-needed-to-show-tonelli-monotone-class-lemma>
#lemma(
  title: [#kn[monotone class lemma]],
)[
Let $cal(A) subset cal(P)\(X\)$ be an algebra. \ Define $cal(C)$ 为包含 $cal(A)$ 的最小的 montone class. \ Claim: $ < cal(A) > = cal(C) $

]
#proof[
$cal(C) subset < cal(A) >$ is trivial. \ $< cal(A) > subset cal(C)$: STS $cal(C)$ 是一个 $sigma$-algebra. see p.66. 具体做法比较 tricky, 但是思路是先证明 $cal(C)$ 是一个 algebra (这一部分较难. 我们对于 $E in cal(C)$, define $cal(C)\(E\)$ 为 $cal(C)$ 中所有和它的交和差也仍然在 $cal(C)$ 中的 $F$ 构成的集合, 并发现这个子集 $cal(C)\(E\)$ 也同样是一个 monotone class. 从而 $cal(C) = cal(C)\(E\)$ );

然后对于任意的 seq, 其 前 $n$ 项的 finite union $\(union_(i = 1)^n E_i\)$seq 是一个 increasing seq, 其 limit 等于原 seq limit, 是属于 $cal(C)$ 的.

]
#remark[
即, 对于一个已经是 algebra 的集合, 它生成的 monotone class 等于它生成的 $sigma$-algebra. \ 这个 lemma 的好处在于, #strong[我们在证明了一个集合是 algebra 后, 证明它是一个 $sigma$-algebra, 只需要证明它 closed under ctbl increasing union 和 decreasing interection 即可. 我们可以利用这种 set seq 的单调性.]

]
但是如果我们只知道 $cal(C) supset cal(A)$, 没有 \"包含 $cal(A)$ 的最小的 monotone class\" 这个条件怎么办? 那也没关系, 我们很自然得出

#corollary(
)[
Let $cal(A) subset cal(P)\(X\)$ be an algebra, $cal(C) supset cal(A)$ be a monotone class, 那么一定有 $ cal(C) supset chevron.l cal(A) chevron.r $

]
因为 $chevron.l cal(A) chevron.r =$ \"包含 $cal(A)$ 的最小的 monotone class\" $subset cal(C)$.

=== Tonelli for sets: integrating a section to get product measure
<tonelli-for-sets-integrating-a-section-to-get-product-measure>
#theorem(
  title: [#kn[Tonelli for sets]],
)[
Let $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$ be #strong[$sigma$-finite] measure spaces. \ Take $E in cal(A) times.o cal(B)$. Then: $ x mapsto nu\(E_x\)\,y mapsto mu\(E_y\)upright(" are measurable ") $ 并且 $ \(mu times nu\)\(E\)= integral nu\(E_x\)#h(0em) d mu\(x\)= integral mu\(E^y\)#h(0em) d nu\(y\) $

]
#remark[
这个定理说明的是: 在 $sigma$-finite 的 measure spaces 构成的 product measure space 中, 任意 product measurable set $E$, 把 $x$ 映射到 $E$ 的 $x$-section 的 measure (#strong[\"扫描\" 这个集合在一个方向上的宽度变化) 的行为是可测的.] \ 并且, 我们可以把 $E$ 的 measure 用 #strong["对每个 $x$, 在 $Y$ 上取 $E$ 的 $x$-section 的 measure, 并对这一行为在 $X$ 上进行积分\"]来刻画. 这就把 product measure 拆分了开来. 其 following 是 Tonelli #strong["把 $n$ 个 measure spaces 的 product 上的积分拆成 $n$ 个积分]\" 的强大定理.

#figure(image("../assets/ch2-pics-image-20250225215218999.png", width: 30.0%),
  caption: [
  ]
)

]
#proof[
Define: $ cal(C) = { E subset X times Y divides x mapsto nu\(E_x\)\,y mapsto mu\(E_y\)upright(" are measurable ") forall\(x\,y\)in E upright(" and") dots.h.c\(2\)} $
#strong[Claim 1:] $cal(C)$ #strong[contains 所有的 rectangles.]
#strong[Proof of Claim 1:] 考虑 $E = A times B in cal(A) times cal(B)$, 即为一个 rectangle. 上一 lec 中, 我们 by def confirm: $cal(A) times cal(B) subset cal(A) times.o cal(B)$. \ 那么对于任意的 $\(x\,y\)in E$, 我们有: $nu\(E_x\)= nu\(B\)$, 对于所有的 $\(x\,y\)in.not E$, 则有 $nu\(E_x\)= diameter$. \ 所以对于任意的 $x$, $nu\(E_x\)= chi_A\(x\)nu\(B\)$, 同理 $mu\(E^y\)= chi_A\(x\)mu\(A\)$. \ 由此得到 $x mapsto nu\(E_x\)\,y mapsto mu\(E^y\)$ 是 measurable 的, 并且 $ mu times nu\(E\)= mu\(A\)times nu\(B\)= mu\(A\)integral chi_B\(y\)#h(0em) d nu\(y\)= integral mu\(E^y\)#h(0em) d nu\(y\) $
同理, $mu times nu\(E\)= integral nu\(E_x\)#h(0em) d mu\(x\)$. 从而得证. 从而, #strong[对于任意 union of finite disjoint rectangles, 这个结论也成立], by additivity in definition. 因而 $cal(C)$ #strong[为一个 algebra.] \ \ Note: 由于 $cal(A) times.o cal(B)$ 为包含所有 rectangles 的最小 $sigma$-algebra, 我们#strong[只需要证明 $cal(C)$ 为一个 $sigma$-algebra], 那么它一定包含 $cal(A) times.o cal(B)$. 并且 by Monotone Class Lemma, #strong[STS: $cal(C)$ 为一个 monotone class.] \ \ #strong[Claim 2: $cal(C)$ 为一个 monotone class.]
令 ${ E_n }$ 为一个 increasing seq in $cal(C)$, 定义其 union 为 $E := union.big_(n = 1)^oo E_n$. 并定义: $ f_n\(y\):= mu\(\(E_n\)^y\) $
根据 $cal(C)$ 的 definition, 每个 $f_n$ 都是 measurable 的, 并且我们容易证明: $ f_n arrow.tr f\(y\):= mu\(\(E\)^y\)upright(" ptwise.") $于是使用 MCT, 容易得到 $ integral mu\(E^y\)#h(0em) d nu\(y\)= lim integral mu\(\(E_n\)^y\)#h(0em) d nu\(y\)= lim mu times nu\(E_n\)=^(upright("CFB")) mu times nu\(E\) $
从而 $E in cal(C)$. \ It remains to show: $cal(C)$ closed under ctbl decreasing intersection. 不过这里我们涉及到一个 decreasing sequence 中间突然从 infinite measure 变为 finite measure 的问题, 所以我们从这里开始要分 $mu\,nu$ finite 和 not finite (but still $sigma$-finite) 的两种情况讨论. finite measure 不用担心上述这一问题. \ #strong[Case 1: $mu\,nu$ finite], 于是令 ${ E_n }$ 为一个 decreasing seq in $cal(C)$, 和 increasing 的情况 similar, 得到 $mu\(\(E_n\)^y\)= : f_n arrow.br f\(y\):= mu\(\(E\)^y\)upright(" ptwise.")$, 从而 by DCT (取 $mu\(X\)$ 为 donimating function), 得到 $ integral mu\(E^y\)#h(0em) d nu\(y\)= lim integral mu\(\(E_n\)^y\)#h(0em) d nu\(y\)= lim mu times nu\(E_n\)=^(upright("CFA")) mu times nu\(E\) $ 从而我们证明了在 $mu\,nu$ 为 finite measure 的情况下, $cal(C)$ 为一个 monotone class, 从而为一个 $sigma$-algebra, 从而 $cal(M) times.o cal(N) subset cal(C)$. \ \ #strong[Case 2: $mu\,nu$ $sigma$-finite measure]: 我们可以把 $X times Y$ 写作 union of a seq of finite measure sets ${ X_i times Y_i }_(i in bb(N))$, 从而也是 a union of increaasing seq of finite measure sets ${ X_j times Y_j }_(j in bb(N))$. (取 $X_j times Y_j = union.big_(i = 1)^j X_j times Y_j$) 从而对于任意的 $E in cal(M) times.o cal(N)$, $ E = lim_(j arrow.r oo)\(E inter\(X_j times Y_j\)\) $
对于每个 $E inter\(X_j times Y_j\)$, 我们可以应用前一结论, 得到 $ mu times nu\(E inter\(X_j times Y_j\)\)= integral chi_(Y_j)\(y\)mu\(E^y inter X_j\)#h(0em) d nu\(y\) $
从而#strong[应用 MCT], 得到 $ mu times nu\(E\)= integral mu\(E^y\)#h(0em) d nu\(y\) $
同理 $mu times nu\(E\)= integral mu\(E_x\)#h(0em) d mu\(x\)$, 从而 $E in cal(C)$, 得证.

]
=== Tonelli's Theorem
<tonellis-theorem>
#theorem(
  title: [#kn[Tonelli]],
)[
Let $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$ be $sigma$-finite measure spaces. \ 条件: 这里所用的非负可测函数积分空间见 #ref[l-space-and-integration-on-it]. \ 令 $f in L^(+)\(X times Y\)$, \ 结论:$ g\(x\):= integral f\(x\,y\)#h(0em) d nu #h(0em) in L^(+)\(X\)quad h\(y\):= integral f\(x\,y\)#h(0em) d mu #h(0em) in L^(+)\(Y\) $ (显然) 并且
$ integral f #h(0em) d\(mu times nu\) & = integral \[ integral f\(x\,y\)#h(0em) d nu\(y\)\] d mu\(x\)\
 & = integral \[ integral f\(x\,y\)#h(0em) d mu\(x\)\] d nu\(y\) $

]
#remark[
Tonelli for sets 表示了 product measure 的计算方式: 通过对 $x$-section 的 $y$ measure, 在 $x in X$ 上进行积分可得到. 这就把 product measure 拆成了单个 measure 与积分. \ 而 Tonelli's Theorem 表示#strong[对一个非负 product measurable function 积分可以转化成对逐个 measure 积分.] \ recall: 非负 measurable 函数的积分, 就是一个 seq of simple functions 的积分的 sup, 而 simple function 的积分, 就是#strong[几个 measurable set 的 measure 的加权和].
因而 Tonelli's Theorem 基本上 naturally follows from Tonelli for sets.

]
#proof[
首先, #strong[对于 $f$ 是 simple function 的 case, 直接 follows from Tonelli for sets.] (mentioned in remark.) \ 对于 general case: $f in L^(+)\(X times Y\)$, 令 ${ f_n }$ 为一个 seq of simple functions ptwisely converging to $f$. \ 于是 $ integral g #h(0em) d mu = lim integral g_n #h(0em) d mu = lim integral f_n #h(0em) d\(mu times nu\)= integral f #h(0em) d\(mu times nu\) $
$ integral h #h(0em) d mu = lim integral h_n #h(0em) d mu = lim integral f_n #h(0em) d\(mu times nu\)= integral f #h(0em) d\(mu times nu\) $
by MCT.

]
== Fubini's Theorem and Lebesgue integral in $bb(R)^n$ \[Fol 2.5, finished; 2.6\]
<fubinis-theorem-and-lebesgue-integral-in-mathbbrn-fol-2.5-finished-2.6>
recall Tonelli's Theorem: Given $f in L^(+)\(X times Y\)$, set $g\(x\):= integral f_x d nu$, $h\(y\):= integral f^y d mu$.
Then $g in L^(+)\(X\)$, $h in L^(+)\(Y\)$, 以及有: $ integral f #h(0em) d\(mu times nu\)= integral g #h(0em) d mu = integral h #h(0em) d nu $
展开后可写作: $ integral f #h(0em) d\(mu times nu\)= integral.double f\(x\,y\)#h(0em) d nu\(y\)d mu\(x\)= integral.double f\(x\,y\)#h(0em) d mu\(x\)d nu\(y\) $更加简洁可写作: $ integral f #h(0em) d\(mu times nu\)= integral.double f #h(0em) d nu d mu = integral.double f #h(0em) d mu d nu $

#corollary(
)[
if $f in L^1\(X times Y\)$ and $f gt.eq 0$ then

- $g\(x\)< oo$ for a.e. $x$

- $h\(y\)< oo$ for a.e. $y$

]
#remark[
在 product measure space 上 measurable 的可积函数, 在每个成分上, 都不能有过多的 infinity point.

]
Next: Fubini's Theorem. \ Fubini's Theorem 是 Tonelli's Theorem 对 $bb(C)$-valued 函数 (instead of $bb(R)_(gt.eq 0)$-valued) 的推广. 但是其实证明很 trivial.

=== Fubini's Theorem
<fubinis-theorem>
#theorem(
  title: [#kn[Fubini's Theorem]],
)[
条件: $f in L^1\(mu times nu\)$, \ 结论:

- $f_x in L^1\(nu\)$ for a.e. $x$, $f^y in L^1\(mu\)$ for a.e.

- The a.e. defined functions: $ g\(x\):= integral f_x #h(0em) d nu in L^1\(mu\)\,quad h\(x\):= integral f^y #h(0em) d nu in L^1\(nu\) $

- $ integral f #h(0em) d\(mu times nu\)= integral g #h(0em) d mu = integral h #h(0em) d nu #h(0em) #h(0em)\(= integral.double f #h(0em) d mu d nu\) $

]
#proof[
$f = Re f + i Im f$, so WLOG can assume $f$ is $bb(R)$-valued. \ 又 $f = f^(+) - f^(-)$, 直接 apply Tonellis's Thm 可得.

]
#remark[
Tonelli and Fubini's Theorem 不仅有用在可以拆分积分以进行计算, 而且有用在积分换序. \ 实际上, 根据它的条件可以发现, 积分可换序的条件是很宽裕的, 只要这个函数 $f$ 在 $L^(+)$ 或者 $L^1$ space 中就可以了.

]
#example(
)[
求和换序的合理性: \ 考虑 $ \(X\,cal(A)\,mu\)=\(Y\,cal(B)\,nu\)=\(bb(N)\,cal(P)\(bb(N)\)\,mu_(c o u n t i n g)\) $if $a_(m n) in bb(C)$ for $\(m\,n\)in bb(N)^2$ and $ oo > sum_(m\,n)\|a_(m n)\|= : sup_(F subset bb(N)^2 upright("finite")) sum_(\(m\,n\)in F)\|a_(m\,n)\| $
Thm: 对于任意 $n in bb(N)$, $sum_m a_(m n)$ conv absly to some $b_n in bb(C)$\; \ 同样, 对于任意 $m in bb(N)$, $sum_n a_(m n)$ conv absly to $c_m in bb(C)$.
以及 $sum_n b_n\,sum_m c_m$ conv absly to $sum_(m\,n) a_(m n)$. \ 即: $ sum_(n = 1)^oo sum_(m = 1)^oo\|a_(m n)\|= sum_(m = 1)^oo sum_(n = 1)^oo\|a_(m n)\|= sum_(\(m\,n\)in bb(N)^2)\|a_(m n)\| $

]
=== complete Fubini's Theorem
<complete-fubinis-theorem>
#remark[
即便 $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$ 都 complete, product space $\(X times Y\,cal(A) times.o cal(B)\,mu times nu\)$ #strong[不一定 complete! (甚至说基本很少 complete)]

]
#example(
)[
考虑 $\(X\,cal(A)\,mu\)=\(Y\,cal(B)\,nu\)=\(bb(R)\,cal(L)\,m\)$
考虑一个 Vitali set. $ V times { 0 } subset bb(R) times { 0 } upright(" is a subnull set, not measurable") $

]
但是如果我们 consider completion: $ \(X times Y\,accent(cal(A) times.o cal(B), macron)\,accent(mu times nu, macron)\) $

#theorem(
  title: [#kn[complete Fubini-Tonelli]],
)[
对于 complete measure space $\(X\,cal(A)\,mu\)$, $\(Y\,cal(B)\,nu\)$, 取它们的 product measure space 的 completion: $ \(X times Y\,accent(cal(A) times.o cal(B), macron)\,accent(mu times nu, macron)\) $
我们将 $accent(cal(A) times.o cal(B), macron)$ 简易写作 $cal(L)$, $accent(mu times nu, macron)$ 简易写作 $lambda$. \ Suppose $f : X times Y arrow.r bb(C)$ is $cal(L)$-measurable 并且 $f in L^(+)\(lambda\)$ or $f in L^1\(lambda\)$, 则有

- $f_x$ 是 $cal(B)$-measurable 的 for a.e. $x$ 且 $x mapsto integral f_x #h(0em) d nu$ 是 measurable 的

- $f_y$ 是 $cal(A)$-measurable 的 for a.e. $y$ 且 $y mapsto integral f_y #h(0em) d mu$ 是 measurable 的

并且, 在 $f in L^1\(lambda\)$ 的情况下, $f_x\,f_y$, $x mapsto integral f_x #h(0em) d nu$, $y mapsto integral f_y #h(0em) d mu$ 也是 #strong[integrable] 的, 即 $in L^1\(lambda\)$, 并且 $ integral f #h(0em) d lambda = integral.double f #h(0em) d mu d nu = integral.double f #h(0em) d nu d mu $

]
#proof[
exercise. 比较简单.

]
#remark[
这一定理的意思是, 在 $mu\,nu$ 是 complete measure 的情况下, $mu times nu$ 的 completion $accent(mu times nu, macron)$ #strong[虽然并不等于 $mu times nu$, 但是 $L^1\(accent(mu times nu, macron)\)$ 的函数的积分却可以当作 $L^1\(mu times nu\)$ 的函数的积分, 从而分成两个积分.]
这是因为 因为完备化测度只是增加了一些#strong[原本测度为零的集合的子集], 这些集合不会影响积分计算. 这一定理的直接应用是 Lebesgue integral on $bb(R)^n$.

]
=== remark: integral of 非负函数等于 area under graph
<remark-integral-of-非负函数等于-area-under-graph>
#theorem(
)[
令 $\(X\,cal(A)\,mu\)$ 为一个 arbitrary measure space, $f in L^(+)\(mu\)$ 为 arbitrary 可测非负函数, 我们定义: $ G_f := {\(x\,y\)in X times\[0\,oo\]: 0 lt.eq y lt.eq f\(x\)} $
Claim: $G_f$ 是 $\(cal(A) times cal(B)\(bb(R)\)\)$-measurable 的, 并且 $ \(mu times m\)\(G_f\)= integral f #h(0em) d mu $

]
#proof[
In hw 6.

]
#remark[
$G_f$ 即 area under the graph of $f$. 这一 statment 是一个#strong[正式的表达 of "integral of 非负函数等于 area under graph\"]. 我们也可以推广它到 $L^1$ 上 (正负 part 的差), which is trivial.

]
