site_name: Numerical Linear Algebra
site_author: qiulinfan
site_url: https://qiulinfan.github.io/qlblog/
use_directory_urls: false
remote_branch: gh-deploy

repo_name: qlblog
repo_url: https://github.com/qiulinfan/qlblog

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Chapters:
    - 01-tensor-products-and-matrix-multiplication: 01-tensor-products-and-matrix-multiplication.md
    - 02-orthogonal-vectors-and-matrices: 02-orthogonal-vectors-and-matrices.md
    - 03-norms: 03-norms.md
    - 04-svd: 04-svd.md
    - 05-qr-factorization: 05-qr-factorization.md
    - 06-discrete-fourier-transform: 06-discrete-fourier-transform.md
    - 07-conditioning-and-stability: 07-conditioning-and-stability.md
    - 08-backward-error-analysis: 08-backward-error-analysis.md
