#import "../../toolchain/math-aliases.typ": *

#let Set(..args) = $lr(brace.l, #args.pos().join(", "), brace.r)$
#let bracket(..args) = $⟨#args.pos().join(", ")⟩$
#let pmat(..args) = math.mat(..args, delim: "(")
#let to = math.arrow.r
#let GL = math.op("GL")
#let adj = math.op("adj")
#let sign = math.op("sign")
#let align(..args) = args.pos().join()

= Homework 7

== 1. Cyclic groups and a sign isomorphism

Let $G$ and $H$ be groups.

(a) Give an example where $G$ and $H$ are both cyclic, but $G times H$ is not.

(b) If $G times H$ is a cyclic group, prove that $G$ and $H$ are both cyclic.

(c) Recall that $bb(R)^times$ is the multiplicative group of units of $bb(R)$. Define an explicit isomorphism $f: bb(R)^times to bb(R) times bb(Z)_2$.

=== (a)

$bb(Z)_2 = bracket(1_2)$ is cyclic, but $bb(Z)_2 times bb(Z)_2$ is not cyclic. It cannot be generated by any element among its four elements, by either addition or multiplication.

=== (b)

*Proof.* Let $(g,h)$ be the generating element such that

$
  bracket((g,h)) = G times H.
$

Take arbitrary $m in G$ and $n in H$. Then $(m,n) = (g,h)^k$ for some integer $k$. Hence $m = g^k$ and $n = h^k$. Therefore $G = bracket(g)$ and $H = bracket(h)$ are cyclic groups.

=== (c)

Let

$
bb(R)^times = Set(a in bb(R) | a != 0).
$

Define $phi: bb(R)^times to bb(R) times bb(Z)_2$ by

$
phi(a) = (ln abs(a), epsilon(a)),
$

Note that $bb(R) times bb(Z)_2$ is an additive group, while $bb(R)^times$ is a multiplicative group.

Take arbitrary $a,b in bb(R)^times$. Then

$
align(
  phi(a) + phi(b)
    &= (ln abs(a),m) + (ln abs(b),n) \
    &= (ln abs(a b),m+n),
)
$

where $epsilon(a)=0_2$ if $a>0$ and $epsilon(a)=1_2$ if $a<0$; likewise $m=epsilon(a)$ and $n=epsilon(b)$. Thus $m+n=0_2$ if $sign(m)=sign(n)$, i.e. if $a b>0$, and $m+n=1_2$ if $sign(m)!=sign(n)$, i.e. if $a b<0$. Therefore

$
phi(a)+phi(b) = phi(a b),
$

so $phi$ is a homomorphism.

Assume $phi(a)=phi(b)$. Then

$
phi(a-b) = phi(a)-phi(b) = (0,0_2).
$

So $ln abs(a)=ln abs(b)$ and $sign(a)=sign(b)$, hence $a=b$. Thus $phi$ is injective.

Let $(m,n) in bb(R) times bb(Z)_2$ be arbitrary. Consider

$
a = e^m (-1)^y,
$

where $y=0$ if $n=0_2$ and $y=1$ if $n=1_2$. Then $phi(a)=(m,n)$, so $phi$ is surjective. Therefore $phi$ is an isomorphism.

== 2. The unit circle

Let $S^1 subset bb(C)$ be the unit circle:

$
S^1 = Set(z in bb(C) | abs(z)=1).
$

(a) Prove that $S^1$ is a subgroup of $bb(C)^times$.

(b) For every positive integer $n$, find an element of order $n$ in $S^1$.

(c) Find an element of infinite order in $S^1$.

=== (a)

*Proof.* As $bb(C)$ is a field, every element except $0$ is a unit in $bb(C)$. Since $0 !in S^1$ and $S^1 subset bb(C)$, $S^1 subset bb(C)^times$. Therefore it suffices to show that $S^1$ contains the identity and that every element has its multiplicative inverse also in $S^1$.

The first statement is true because $abs(1)=1$. For the second, consider $a+b i in S^1$. Since $sqrt(a^2+b^2)=1$,

$
(a+b i)(a-b i) = a^2+b^2 = 1,
$

so $a-b i$ is the multiplicative inverse of $a+b i$. Therefore $S^1$ is a subgroup of $bb(C)^times$.

=== (b)

By Euler's formula,

$
e^(2 pi i) = cos(2 pi)+i sin(2 pi)=1,
$

so $e^(2 pi i) in S^1$ and is the identity. For arbitrary $n in bb(Z)_(>=1)$, consider

$
e^(2 pi i / n)=cos(2 pi/n)+i sin(2 pi/n) in S^1.
$

Because

$
(e^(2 pi i/n))^n=e^(2 pi i)=1,
$

the order of $e^(2 pi i/n)$ is $n$.

=== (c)

Consider

$
e^(sqrt(2) pi i)=cos(sqrt(2) pi)+i sin(sqrt(2) pi).
$

For every $n in bb(Z)_(>=1)$,

$
(e^(sqrt(2) pi i))^n=e^(sqrt(2) pi i n) != e^(2 pi i),
$

since $sqrt(2)$ is irrational. Thus its order is infinite.

== 3. Units in matrix rings

Let $R$ be a commutative ring, and consider the group $GL_2(R)$ of units in the ring of $2 times 2$ matrices $M_2(R)$.

(a) Suppose $A = mat(a,c; b,d) in M_2(R)$ and all entries are in an ideal $I subset.neq R$. Prove that $A$ is not a unit.

(b) Prove that for $A=mat(a,b;c,d) in M_2(R)$ there is a matrix $B$ such that $A B=B A=det(A)I_2$.

(c) Prove that $A in M_2(R)$ is a unit if and only if $det(A)$ is a unit.

=== (a)

*Proof.* Assume for sake of contradiction that $A$ is a unit. Then there is $B in M_2(R)$ such that

$
A B=B A=I_2=mat(1,0;0,1),
$

where $1$ is the multiplicative identity of $R$. Denote $B$ by $mat(m,n;p,q)$. Then

$
A B=mat(a m+b p, a n+b q; c m+d p, c n+d q)=I_2.
$

Since $a,b in I$ and $m,p in R$, $a m,b p in I$, hence $a m+b p in I$ because $I$ is closed under addition. Therefore $1 in I$, so $I=R$, which contradicts $I subset.neq R$. Thus $A$ is not a unit.

=== (b)

For $A=mat(a,b;c,d) in M_2(R)$, consider

$
B=adj(A)=mat(d,-b;-c,a) in M_2(R).
$

Then, since $R$ is commutative,

$
align(
  A B=B A
    &= mat(a d-b c,b c-a b;a b-b a,d a-c b) \
    &= mat(a d-b c,0;0,a d-b c) \
    &= (a d-b c)I_2 = det(A)I_2.
)
$

=== (c)

Since $R$ is a commutative ring, $det(A B)=det(A)det(B)$ for $A,B in M_2(R)$.

*Claim 1.* If $A$ is a unit in $M_2(R)$, then $det(A)$ is a unit in $R$.

*Proof.* Assume $A=mat(a,b;c,d) in M_2(R)$ is a unit. Then there is $C=mat(m,n;p,q) in M_2(R)$ such that $A C=C A=I_2$. Hence

$
det(A)det(C)=det(I_2)=1
$

and also $det(C)det(A)=1$ in $R$. Therefore $det(A)$ is a unit in $R$ by definition.

*Claim 2.* If $det(A)$ is a unit in $R$, then $A$ is a unit in $M_2(R)$.

*Proof.* Assume $det(A)$ is a unit in $R$. Then there is $m in R$ such that

$
m det(A) = det(A)m = 1.
$

By part (b), there is $B in M_2(R)$ such that $B A=A B=det(A)I_2$. Consider $C=(det(A))^(-1)B=m B$. Then

$
C A=A C=(m det(A))I_2=I_2.
$

Therefore $A$ is a unit in $M_2(R)$. By Claims 1 and 2, $A$ is a unit in $M_2(R)$ if and only if $det(A)$ is a unit in $R$.

== 4. Matrices over $bb(Z)_p$

Let $p$ be a prime number and consider the field $bb(Z)_p$.

(a) Show that a $2 times 2$ matrix $A in M_2(bb(Z)_p)$ is not a unit if and only if the columns are linearly dependent.

(b) Show that the set of upper triangular invertible matrices in $GL_2(bb(Z)_p)$ forms a subgroup of order $p(p-1)^2$, which is non-abelian when $p != 2$.

(c) Compute the order of $GL_2(bb(Z)_p)$.

(d) Show that diagonal invertible matrices form an abelian subgroup of $GL_2(bb(Z)_p)$ of order $(p-1)^2$.

(e) Find an abelian subgroup of $GL_2(bb(Z)_p)$ of order $p$.

=== (a)

*Claim 1.* $A=mat(a,b;c,d) in M_2(bb(Z)_p)$ is not a unit if the columns are linearly dependent.

*Proof.* Assume the columns of $A$ are linearly dependent. Then

$
m vec(a,c) + n vec(b,d)=vec(0,0)
$

where $m,n in bb(Z)_p$ are not both $0$. Without loss of generality, assume $m != 0$. Since $bb(Z)_p$ is a field, $m^(-1) in bb(Z)_p$, so

$
vec(a,c)=-m^(-1)n vec(b,d),
$

which gives $det(A)=a d-b c=0$. This is not a unit. Since $bb(Z)_p$ is a field and hence a commutative ring, problem 3 shows that $A in M_2(bb(Z)_p)$ is a unit if and only if $det(A)$ is a unit in $bb(Z)_p$. Thus $A$ is not a unit.

*Claim 2.* If $A in M_2(bb(Z)_p)$ is not a unit, then the columns are linearly dependent.

Assume $A$ is not a unit and the columns are not linearly dependent. Then $det(A) != 0_p$. Let $det(A)=m$. Consider

$
B=m^(-1)mat(d,-b;-c,a).
$

Then $A B=B A=I_2$, contradicting that $A$ is not a unit. So the columns are linearly dependent. Therefore $A in M_2(bb(Z)_p)$ is not a unit if and only if the columns of $A$ are linearly dependent.

=== (b)

The set of upper triangular invertible matrices in $GL_2(bb(Z)_p)$ is

$
S=Set(mat(a,b;0,c) | a,b,c in bb(Z)_p " and " a,c != 0_p).
$

Since $I_2 in S$, and for $A=mat(a,b;0,c) in S$ we have $a,c != 0$, take

$
B=(a c)^(-1)mat(c,-b;0,a) in S.
$

Then $A B=B A=I_2$, so every element in $S$ has its inverse also in $S$. Thus $S$ is a subgroup of $GL_2(bb(Z)_p)$.

There are $p-1$ different choices for $a$, $p-1$ different choices for $c$, and $p$ different choices for $b$. The three choices are independent, so there are $p(p-1)^2$ elements in $S$.

Take $mat(1,1;0,p-1)$ and $mat(1,1;0,1)$ in $S$. Then

$
mat(1,1;0,p-1)mat(1,1;0,1)=mat(1,2;0,p-1),
$

whereas

$
mat(1,1;0,1)mat(1,1;0,p-1)=mat(1,p;0,p-1).
$

Since these are different if $p!=2$, $S$ is non-abelian when $p!=2$.

When $p=2$, consider arbitrary $mat(a,b;0,c),mat(m,n;0,p) in S$. Since $a,c,m,p != 0$, we have $a=c=m=p=1$, and

$
mat(a,b;0,c)mat(m,n;0,p)=mat(a m,a n+b p;0,c p)=mat(1,b+n;0,1)
$

and

$
mat(m,n;0,p)mat(a,b;0,c)=mat(a m,b m+c n;0,c p)=mat(1,b+n;0,1).
$

Thus $S$ is abelian if $p=2$.

=== (c)

By part (a), $A in M_2(bb(Z)_p)$ is a unit, i.e. $A in GL_2(bb(Z)_p)$, if and only if the columns of $A$ are linearly independent. First choose an arbitrary nonzero vector $vec(a,b) in bb(Z)_p^2$; there are $(p^2-1)$ choices. Then choose a vector $v$ which is linearly independent with it, i.e. $v ∉ Set(k vec(a,b) | k in bb(Z)_p)$. There are $(p^2-p)$ choices for the second column. Hence

$
abs(GL_2(bb(Z)_p))=(p^2-1)(p^2-p).
$

=== (d)

The set of diagonal invertible matrices is

$
S=Set(mat(a,0;0,b) in M_2(bb(Z)_p) | a,b != 0).
$

There are $p-1$ choices for $a$ and $p-1$ choices for $b$, so $abs(S)=(p-1)^2$. To show it is a subgroup, $I_2 in S$, and for $A=mat(a,0;0,b) in S$ consider

$
B=(a b)^(-1)mat(b,0;0,a).
$

Then $B A=I_2$, so $A$ has an inverse. Therefore $S$ is a subgroup of $GL_2(bb(Z)_p)$ whose order is $(p-1)^2$. It is abelian because, for $A=mat(a,0;0,b)$ and $B=mat(c,0;0,d)$ in $S$,

$
A B=B A=mat(a c,0;0,b d).
$

=== (e)

$bracket(mat(1,1;0,1))$ is a subgroup of $GL_2(bb(Z)_p)$ whose order is $p$. This is a subgroup guaranteed by generating a cyclic subgroup from an element in the group. Also,

$
mat(1,1;0,1)^n=mat(1,n;0,1),
$

so $mat(1,1;0,1)^p=mat(1,p;0,1)=I_2$, while $mat(1,1;0,1)^n != I_2$ for $1<=n<=p-1$. Hence its order is $p$.
