#import "../../../toolchain/typst-template/qlnotes.typ": *
#import "../../../toolchain/typst-template/math-aliases.typ": *
#import "../diagrams/probability-diagrams.typ": *

= random variable
<random-variable>
== random variable and generated $sigma$-algebra
<random-variable-and-generated-sigma-algebra>
=== random variable: 即 prob space 上的一个 Borel measurable function
<random-variable-即-prob-space-上的一个-borel-measurable-function>
#definition(
  title: [random variable],
  id: "def-02-random-variables-random-variable",
  concepts: ("random-variable",),
  depends: (),
  aliases: ("random variable",),
)[
对于 probability space $\(Omega\,cal(F)\,bb(P)\)$, 一个 random variable 是一个 #strong[Borel measurable function] $X : Omega arrow.r bb(R)$.

]
#remark[
回顾 (Borel) measurable function 的定义:
即对于任意 $B in cal(B)\(bb(R)\)$, 有 $X^(- 1)\(B\)in cal(F)$\;
由于是在 real space 上, Borel measurable 也可以简化为:
对于任意的 open ray $\(- oo\,a\)$, 有
$X^(- 1)\(\(- oo\,a\)\)in cal(F)$.

例如: $X\(omega\)= omega^2$ 是一个 (Borel) measurable function,
因为对于任意 open ray $\(- oo\,a\)$,
$X^(- 1)\(\(- oo\,a\)\)$ 是一个
interval (either $\(- sqrt(a)\,sqrt(a)\)$
or $nothing$).

并且 recall: 任意的 continuous function 都是 (Borel) measurable function.
(所以之后我们看到 continuous function 就知道它一定是一个 random variable).

]
#remark[
Random variable (Borel measurable function) 本质上是对
样本空间中的事件进行 weights assignment.

原本, 一个 prob space 只能表示: #strong[有多少个 outcomes, 每个 outcome 的概率是多少]
(对于无限的 sample space, 一些 outcomes 组合, 即事件, 的概率是多少).

而 random variable 就是#strong[给这些 outcomes 以 weights]: 比如

#example(
  id: "ex-02-random-variables-example-001",
  concepts: ("example-001",),
  depends: (),
)[
在一副扑克牌中抽一张, 那么每一张的概率都是 $1\/52$.
但是如果我想知道抽到的牌的价值,
那么我就需要一个 random variable $X$ 来给每一张牌赋予一个 weight;
比如说, $X\(upright("A")\)= 1$, $X\(upright("2")\)= 2$, $dots.h.c$, $X\(upright("K")\)= 13$. \

]
#strong[Question]: 为什么对于 assigning weights 的行为, 我们一定要求它是一个 (Borel) measurable function 呢?
普通的给 outcomes 以 weights 的行为 (任意一个 function $f : Omega arrow.r bb(R)$) 不行吗?

#strong[Answer]:
因为我们想要知道 $X$ 的值在一个范围 $B$, 比如 $\[1\,6\]$
之内的 probability (which is defined on
原本的 prob measure $bb(P)$ 上的) 是多少. 而只有每一个这样的范围集合的
preimage $X^(- 1)\(B\)$ 都是 $cal(F)$ 中的事件,
我们才能够通过 $bb(P)$ 来计算这个 probability; that is,
我们需要这个 $X$ 是一个 measurable function.

因为这一切都是建立在我们以 measure theory 的 framework
来定义 probability 的基础上的. \

]
下面是一个简单的 proposition: 我们可以把多个 random variables
以一种 Borel measurable 的方式组合起来, 那么就成为一个新的 random variable.

#proposition(
  title: [以 Borel measurable 的方式组合起多个 random variables],
  id: "prop-02-random-variables-borel-measurable-random-variables",
  concepts: ("-borel-measurable-random-variables",),
  depends: (),
  aliases: ("以 Borel measurable 的方式组合起多个 random variables",),
)[
Prob space $\(Omega\,cal(F)\,bb(P)\)$ 上的
random variables $X_1\,X_2\,dots.h\,X_k : Omega arrow.r bb(R)$,
任取 Borel measurable function $g : bb(R)^k arrow.r bb(R)$,
$ X : Omega & arrow.r bb(R)\
omega & mapsto g\(X_1\(omega\)\,X_2\(omega\)\,dots.h\,X_k\(omega\)\) $
也是一个 random variable.

]
#proof[
我们在 measure theory 中证明过: 对于任意的 finite seq of Borel measureable functions
$\(f_i : Omega arrow.r bb(R)\)_(i = 1)^k$, 其各作为一个维度组成的函数
$f =\(f_1\,dots.h.c\,f_k\)$ 也是一个 Borel measurable function (from $Omega$ 到 $bb(R)^k$). \ 而这里的 $X$ 就是 $g compose f$, 是两个 Borel measurable function 的 composition, 因而也是一个 Borel measurable function (即 random variable).

]
#remark[
以一种 Borel measurable 的方式组合多个 random variables,
这个函数也仍然是一个 random variable.

这个 proposition 看似没有什么卵用, 但是它其实是我们之后构造
random variable 的一个重要工具.
很多我们默认合法的行为, 它都作为基础.

比如我们:

- 定义了两个 random variable $X$ 和 $Y$, 那么它们的和 $X + Y$ 以及积 $X dot.op Y$ 也是 random variables.

- 更加复杂的: 标量变换 $g\(X\)= sin\(X\)\,h\(X\)= e^X$, 向量变换 $g\(X_1\,X_2\)= X_1^2 + X_2^2$, 等等, 都是 random variables.

- 统计学中,
  我们有一堆样本, #strong[每一个都是随机采样得到的 (即一个 random variable $X_i$)]. 因而在观测之前, 我们
  把它看作一个 random variable $X_i$, 然后在观测之后取到它的一个实际值 $x_i$.

  通常我们假设所有样本都是
  #strong[independent and identically distributed (i.i.d., 独立同分布)] 的, 即所有的
  $X_1\,X_2\,dots.h\,X_n$ 都是 independent 的, 并且服从同一个 distribution (discuss later...).

  然后, 我们就可以从这些样本中计算各种统计量, 比如平均值 $macron(X) := 1 / n sum_(i = 1)^n X_i$,
  再比如 order statistic, sample variance 等等, 从而通过大数定律等工具的辅佐, 来估计这个 distribution
  到底是什么样的一个 distribution.

  这里这些统计量, 由于是以 Borel measurable 的方式组合起多个 random variables, 也是 random variables.
  所以这个 proposition 其实也奠定了统计学中各种统计量的合法性.

]
=== 由一个 random variable generate 的 $sigma$-algebra
<由一个-random-variable-generate-的-sigma-algebra>
#definition(
  title: [$sigma$-algebra generated by a random variable (measurable function)],
  id: "def-02-random-variables-sigma-algebra-generated-by-a-random-variable-measurable-function",
  concepts: ("sigma-algebra-generated-by-a-random-variable-measurable-function",),
  depends: (),
  aliases: ("\\sigma-algebra generated by a random variable (measurable function)",),
)[
对于 random variable $X : Omega arrow.r bb(R)$,
其 generate 的 $sigma$-algebra 定义为
$ sigma\(X\):= { X^(- 1)\(B\): B in cal(B)\(bb(R)\)} subset.eq cal(F) $

]
这个集合 $sigma\(X\)$ 是一个 $sigma$-algebra, 是一个 trivial truth. 因为
里面所有的 set 都是 $X$ 的 preimage, 而 $X$ 是一个 measurable function,
因而任意的 $X^(- 1)\(B\)in cal(F)$.

这个 $sigma\(X\)$ 也是让 $X$ 成为一个 measurable function (即 random variable)
的最小的 $sigma$-algebra. 它的意义是:
#strong[当我们仅仅观察到 $X$ 的取值时, 我们所掌握的关于
underlying sample space $Omega$ 的全部 \"information\".]

#remark[
我们知道, #strong[一个 $sigma$-algebra $cal(F)$ 可以看作是一个 information structure]:
它是对 underlying sample space $Omega$ 进行划分的一个工具. \ 最大的 $sigma$-algebra $cal(P)\(Omega\)$, 即 power set, 是
最细的划分, 也是信息量最大的 $sigma$-algebra. 它把每一个元素都区分开来. 对于 discrete 的
sample space, 通常我们的 probability measure 就是定义在 power set 上的, 正是因为我们
希望区分每一个 outcome. \ 而给定一个 prob space $\(Omega\,cal(F)\,bb(P)\)$, 原本的 prob measure 所 base on 的
$sigma$-algebra $cal(F)$ 就成为了一个基准的 information 的颗粒度:
哪些事件是我们可以区分, 即可以在上面定义 probability 的.

而一个 random variable $X$ 可能会把多个 outcomes 映射到同一个值上, 也即
把多个 events 映射到同一个值上, 从而把这些 events 区分不开来.
因而, #strong[random variable $X$ generate 的 $sigma$-algebra $sigma\(X\)$ 就可能是一个更粗的划分].
当我们取这些 events 所映射到的同一个值的 preimage 的时候, 取到的是
它们的 union, 也就是它们中最大的一个.

比如

#example(
  id: "ex-02-random-variables-example-002",
  concepts: ("example-002",),
  depends: (),
)[
掷一次骰子, 所有可能结果为 sample space: $ Omega = { 1\,2\,3\,4\,5\,6 } $
而我们定义一个 random variable $X$ 来表示掷出的点数的奇偶性, 即:
$ X\(omega\)= cases(delim: "{", 1\, & omega in { 2\,4\,6 }, 0\, & omega in { 1\,3\,5 }) $
那么它 generate 的 $sigma$-algebra:
$ sigma\(X\)= #scale(x: 120%, y: 120%)[{] nothing\,{ 1\,3\,5 }\,{ 2\,4\,6 }\,Omega #scale(x: 120%, y: 120%)[}] $
因为 $1\,3\,5$ 这些事件都被映射到了同一个值 $0$ 上, 即
${ 1 }\,{ 3 }\,{ 5 }\,{ 1\,3 }$ 这些事件都被 ${ 1\,3\,5 }$ 这个
事件吸收了, 它们在这个 random variable $X$ 的映射下是区分不开的. 这就代表了
这个 random variable 所蕴含的信息颗粒度:
#strong[我们只能区分掷出的点数是奇数还是偶数, 但是无法区分具体的点数是多少.] \ 至此我们知道: #strong[一个 random variable $X$ 的 generate 的 $sigma$-algebra
$sigma\(X\)$ 表示了这个 random variable 对 underlying sample space
$Omega$ 所能区分的 information granularity (信息颗粒度)]. \

]
]
除了能表示 information granularity 以外,
$sigma\(X\)$ 还有什么实际用处呢:

- 之后讨论关于 independence of two random variables $X$ 和 $Y$ 时,
  可以用它来作严格定义, 并且展现 independence 的本质: 两个 RV 的 independence 实际表示它们蕴含的信息颗粒度之间没有任何 overlap

- 用以定义 conditional expectation: $bb(E)\[Y\|sigma\(X\)\]$, 通常
  简写为 $bb(E)\[Y\|X\]$, 但是其实 $bb(E)\[Y\|sigma\(X\)\]$
  是一个更加直观的事情, 表述了一种 Partial Averaging 的概念.

- Stochastic Process 中有众多应用. 比如 stopping time 的定义.

至此关于 random variable, 我们已经讨论了很多 general 的
刻画. 现在我们来讲一点实用的:

== distributions
<distributions>
=== distribution and cumulative distribution function
<distribution-and-cumulative-distribution-function>
#definition(
  title: [probability distribution],
  id: "def-02-random-variables-probability-distribution",
  concepts: ("probability-distribution",),
  depends: (),
  aliases: ("probability distribution",),
)[
对于 random variable $X : Omega arrow.r bb(R)$ on $Omega\,cal(F)\,bb(P)$,
其 probability distribution 是 $X$ 对于 $bb(P)$ 的 pushforward measure,
记作 $bb(P)^X : cal(B)\(bb(R)\)arrow.r\[0\,1\]$. 即
$ bb(P)^X\(B\):= bb(P)\(X^(- 1)\(B\)\)\,quad forall B in cal(B)\(bb(R)\) $
我们 write:
$ X tilde.op bb(P)^X $

]
#remark[
看着有点不直观. 实则我们拆解:

- $X^(- 1)\(B\)$ 即: 有多少 samples (即哪一个事件 $E in cal(F)$) 在这个 RV $X$ 的映射下落入 $B$ 这个区间?

- $bb(P)\(X^(- 1)\(B\)\)$ 即: 这个事件 $E$ 的概率是多少?

接下来的定义和例子会更加直观.

]
#definition(
  title: [distribution function (也称 #strong[cumulative distribution function,
cdf])],
  id: "def-02-random-variables-distribution-function-cumulative-distribution-function-cdf",
  concepts: ("distribution-function-cumulative-distribution-function-cdf",),
  depends: (),
  aliases: ("distribution function (也称 cumulative distribution function, cdf)",),
)[
对于 random variable $X : Omega arrow.r bb(R)$,
其 #strong[cumulative distribution function] 是 $bb(P)^X$ 这一函数的 distribution function,
记作 $F_X$. 即对于任意 $x in bb(R)$, 有
$ F_X\(x\):= bb(P)^X\(\(- oo\,x\]\)= bb(P)\(X^(- 1)\(\(- oo\,x\]\)\) $

]
#remark[
$F_X\(x\)$ 即 $bb(P)\({ X lt.eq x }\)$ 我们也会简写为 $bb(P)\(X lt.eq x\)$. \ $F_X\(x\)$ 的意义是: random variable $X$ 的值不超过 $x$ 的概率. \

]
#example(
  title: [\(geometric probability)],
  id: "ex-02-random-variables-geometric-probability",
  concepts: ("geometric-probability",),
  depends: (),
  aliases: ("(geometric probability)",),
)[
Fix $a\,b > 0$.
我们在正方形区域 $Omega =\[0\,a\]times\[0\,b\]$ 上均匀地随机选取一个点 $\(x\,y\)$. \ 我们 define 随机变量: $X : Omega arrow.r bb(R)$ by $X\(x\,y\)= x$. 求 $X$ 的 distribution function $F_X$. \ 这很简单: 对于 $x in\[0\,a\]$,
$ F_X\(x\)= bb(P)\(X lt.eq x\)= frac(m\(\[0\,x\]times\[0\,b\]\), m\(\[0\,a\]times\[0\,b\]\)) = frac(x dot.op b, a dot.op b) = x / a\,quad 0 lt.eq x lt.eq a $
因为
$ F_X\(x\)= cases(delim: "{", 0\, & x < 0, x / a\, & 0 lt.eq x lt.eq a, 1\, & x > a) $
注意: 在这个例子中, probability measure $P$ 是 Lebesgue measure on $\[0\,a\]times\[0\,b\]$. 很多时候我们在
计算 RV 的 distribution function 的时候, 都是直接直观地计算 $P\(X lt.eq x\)$. 但是在稍微复杂一些
的例子中, 我们需要对各个条件的 formalization 更清楚一点.

]
#theorem(
  title: [distribution function 的性质],
  id: "thm-02-random-variables-distribution-function",
  concepts: ("distribution-function",),
  depends: (),
  aliases: ("distribution function 的性质",),
)[
对于 random variable $X : Omega arrow.r bb(R)$, 其 distribution function $F_X$ 满足:

- $F_X$ 是 non-decreasing (non-strictly increasing) 的.

- $lim_(x arrow.r + oo) F_X\(x\)= 1$, $lim_(x arrow.r - oo) F_X\(x\)= 0$.

- $F_X$ 是 right-continuous 的. 即对于任意 $x_0$, 有 $lim_(x arrow.r x_0^(+)) F_X\(x\)= F_X\(x_0\)$.

- 对于任意 $x_0$, 有 $lim_(x arrow.r x_0^(-)) F_X\(x\)= P\(X < x_0\)$.
  并且 $bb(P)\(X = x_0\)= lim_(x arrow.r x_0^(+)) F_X\(x\)- lim_(x arrow.r x_0^(-)) F_X\(x\)$.

- 对于任意 $x_1 < x_2$, 有 $P\(X in\(x_1\,x_2\]\)= F_X\(x_2\)- F_X\(x_1\)$.

]
#proof[
其他都显然. right-continuity 是源自 measure 的 continuity from above,
我们证明一下: 考虑一个单调递减序列 ${ x_n } arrow.b x_0$,
令 seq of events $A_n = { X lt.eq x_n }$, 注意这是一个嵌套递减的 set seq.
通过 $bb(R)$ 的 completeness 容易证明: $ A_0 = inter.big_(n = 1)^oo A_n = { omega : X\(omega\)lt.eq x_0 } $
由 measure 的 continuity from above, $bb(P)\(A_0\)= lim_(n arrow.r oo) bb(P)\(A_n\)$.
也即 $lim_(x arrow.r x_0^(+)) F_X\(x\)= bb(P)\(X lt.eq x_0\)$. \ 而下面一条 $lim_(x arrow.r x_0^(-)) F_X\(x\)= bb(P)\(X < x_0\)$ 同理是源自 measure 的
continuity from below. \ 那么 $bb(P)\(X = x_0\)= bb(P)\(X lt.eq x_0\)- bb(P)\(X < x_0\)$ 是 natural 的 (by def).

]
#remark[
我们此时心里会默认一件事情: 一旦知道了 RV $X$ 的 distribution function
$F_X$, 就知道了 $X$ 的完整 distribution $P^X$.
这个直觉是对的. \ 回忆一下: 我们在 measure theory 中,
证明 Carathéodory extension theorem 的时候,
证明过一个 $pi - lambda$ theorem, 以它作为工具才
把 premeasure 从一个 algebra extend
到一个 measure on the generated $sigma$-algebra:

#theorem(
  title: [Dynkin's $pi - lambda$ theorem],
  id: "thm-02-random-variables-dynkins-pi-lambda-theorem",
  concepts: ("dynkins-pi-lambda-theorem",),
  depends: (),
  aliases: ("Dynkin’s \\pi-\\lambda theorem",),
)[
设 $cal(P)$ 是一个 $pi$-system (closed under finite intersection), $cal(L)$ 是一个 $lambda$-system
(closed under complementation and countable disjoint union),
如果 $cal(P) subset.eq cal(L)$, 那么 $sigma\(cal(P)\)subset.eq cal(L)$.

]
我们考虑所有的 half-open interval $\(- oo\,x\]$ 组成的集合
$cal(G)$, 这个集合 generate the Borel $sigma$-algebra, 并且
还是一个 $pi$-system, 即: 它 closed under finite intersection:
$ \(- oo\,a\]inter\(- oo\,b\]in cal(G)\,quad forall a\,b in bb(R) $
然后考虑 $ cal(L) := { E in sigma\(cal(G)\): bb(P)_1\(E\)= bb(P)_2\(E\)} $
即两个 measure 一致的 collection of sets.
容易证明, 这个 $cal(L)$ 是一个 $lambda$-system, 并且 $cal(G) subset cal(L)$. \ 从而, $ bb(B)\(bb(R)\)= sigma\(cal(G)\)subset.eq cal(L) $ 并且 $bb(P)_1\(E\)= bb(P)_2\(E\)$
对于任意 $E in bb(B)\(bb(R)\)$.

因而:

#corollary(
  title: [distribution function $F_X$ determines distribution $bb(P)^X$],
  id: "cor-02-random-variables-distribution-function-f-x-determines-distribution-mathbb-p-x",
  concepts: ("distribution-function-f-x-determines-distribution-mathbb-p-x",),
  depends: (),
  aliases: ("distribution function F_X determines distribution \\mathbb{P}^X",),
)[
对于 random variable $X : Omega arrow.r bb(R)$, 其 distribution function $F_X$ 确定了 distribution $bb(P)^X$\; 即
如果两个 random variable $X$ 和 $Y$ 满足 $F_X = F_Y$, 那么 $bb(P)^X = bb(P)^Y$.

]
]
=== discrete random variable 与 probability mass function
<discrete-random-variable-与-probability-mass-function>
我们基本上研究两类 random variable: discrete random variable 和 continuous random variable.

#definition(
  title: [discrete random variable],
  id: "def-02-random-variables-discrete-random-variable",
  concepts: ("discrete-random-variable",),
  depends: (),
  aliases: ("discrete random variable",),
)[
对于 random variable $X : Omega arrow.r bb(R)$,
如果存在一个 countable set $S subset.eq bb(R)$
使得 $bb(P)\(X in S\)= 1$,
那么 $X$ 是一个 discrete random variable.

]
#remark[
就是说, #strong[$X$ 的 range a.s. 是 countable 的] (允许 null set 上
的值不在这个 countable set 里, 但是这是 measure theory
下的概念, 所以这些都可以忽略不计).

]
#remark[
对于 discrete random variable $X$,
其 distribution function $F_X$ 是一个 step function,
只有 countable 多个 jump discontinuity,
每个 jump 的大小就是 $X$ 在那个点的 probability mass. \ 因而, 对于 discrete random variable $X$,
通常考虑其 #strong[probability mass function (pmf)] $p_X$ 更加有用:

#definition(
  title: [probability mass function (pmf)],
  id: "def-02-random-variables-probability-mass-function-pmf",
  concepts: ("probability-mass-function-pmf",),
  depends: (),
  aliases: ("probability mass function (pmf)",),
)[
对于 discrete random variable $X$, 其 pmf 定义为
$ p_X\(x\):= bb(P)\(X = x\)\,quad forall x in bb(R) $

]
这个 pmf 就是 $F_X$ 的 jump size function.
当然, 根据定义明显可得: $ sum_x p_X\(x\)= 1 $

]
值得一提的是,
这个 #strong[pmf 其实就是 $X$ 的 distribution $bb(P)^X$ 对于 counting measure (for range of $X$)的 Radon-Nikodym derivative:]

#proposition(
  title: [pmf 是 distribution 对于 counting measure $mu_S$ 的 Radon-Nikodym 导数],
  id: "prop-02-random-variables-pmf-distribution-counting-measure-mu-s-radon-nikodym",
  concepts: ("pmf-distribution-counting-measure-mu-s-radon-nikodym",),
  depends: (),
  aliases: ("pmf 是 distribution 对于 counting measure \\mu_S 的 Radon-Nikodym 导数",),
)[
对于一个 discrete random variable $X$, 假设其 range 是 countable set $S$,
则我们定义 counting measure $mu_S$ on $S$ 为: $ mu_S\(A\):= sum_(x_i in S) upright(bold(1))_A\(x_i\) $
那么, distribution $bb(P)^X lt.double mu_S$ (绝对连续), 并且有:
$ p_X = frac(d bb(P)^X, d mu_S) $

]
#proof[
这很容易证明. 首先, 这个 counting measure 即:
$A$ 中有多少个点在 $S$ 中. \ 那么显然, 如果 $mu_S\(A\)= 0$, 即 $A$ 中没有点在 $S$ 中,
那么 $bb(P)^X\(A\)= 0$. 因而 $bb(P)^X lt.double mu_S$. \ 且对于任意 Borel set $A$,
$ bb(P)^X\(A\)= sum_(x_i in A) bb(P)\(X = x_i\)= sum_(x_i in A inter S) p_X\(x_i\)= integral_A p_X\(x\)#h(0em) d mu_S\(x\) $

]
=== continuous random variable 与 probability density function
<continuous-random-variable-与-probability-density-function>
相对应 discrete random variable, 我们定义 continuous random variable:

#definition(
  title: [continuous random variable],
  id: "def-02-random-variables-continuous-random-variable",
  concepts: ("continuous-random-variable",),
  depends: (),
  aliases: ("continuous random variable",),
)[
我们称一个 random variable $X : Omega arrow.r bb(R)$
是一个 #strong[continuous random variable], 如果它的 cdf $F_X$ 是一个
#strong[absolutely continuous function.]

]
#remark[
回顾 absolutely continuous function 的定义, 这是一个比较复杂的定义:
对于任意 $epsilon.alt > 0$, 都存在 $delta > 0$
使得任取 finite collection of
disjoint intervals ${\(a_i\,b_i\)}$, 都满足:
$ sum_i\(b_i - a_i\)< delta arrow.r.double.long sum_i\|F_X\(b_i\)- F_X\(a_i\)\|< epsilon.alt $
这是 uniform continuity 的一个加强版本. uniform continuity 对应的是 $n = 1$
的情况, 即: #strong[任意的区间上, 只要长度足够小, 就能保证 $F_X$ 在这个区间上的增量足够]小;
而 absolutely continuity 更严格:
#strong[即便是任意数量的分散的区间, 只要总长度足够小, 就能保证 $F_X$ 在这些 interval 上的增量的总和足够小.]

这个定义有点麻烦, 不过存在等价的条件. 为此我们要 recall 一系列定义与结论, 详细请见: #link("https://qiulinfan.github.io/mathnotes-measure_theory/12-differentiation_on_real_spaces.html")[notes on measure theory, module 12: differentiation on $bb(R)$]:

- 给定一个 function $F : bb(R) arrow.r bb(C)$, 我们定义它的
  #strong[total variation function] $V_F : bb(R) arrow.r\[0\,+ oo\]$ 为: $ T_F\(x\):= sup #scale(x: 120%, y: 120%)[{] sum_(i = 1)^n\|F\(x_i\)- F\(x_(i - 1)\)divides - oo < x_0 < dots.h.c < x_n #scale(x: 120%, y: 120%)[}] $ ~

- 如果 $T_F\(oo\)< oo$ (注意这是单调递增函数, 因而即对于任意的 $x$ 都有 $T_F\(x\)< oo$), 那么我们称 $F$ 是一个 #strong[function of bounded variation], 写作 $F in B V$.

- 如果 $F in B V$, 且 $F$ 是 right-continuous 的, 且 $F\(- oo\)= 0$, 那么我们称 $F in N B V$. (即 normalized function of bounded variation).

- #strong[任意的 $F in N B V$ 都 $m$-a.e. differentiable, 且导数 $F' in L^1\(m\)$], 并且以下三个条件等价:
  $  & quad quad F in A C\
   & arrow.l.r.double mu_F lt.double m\
   & arrow.l.r.double F\(x\)= integral_(- oo)^x F'\(t\)#h(0em) d t quad forall x in bb(R) $

]
这几行字浓缩了 measure theory 的 differentiation theory 的两个星期的内容...
具体见上文 notes 链接, 都有详细证明.
而我们这里就利用起最后这一条结论. 首先, 我们 state 一件事:

#lemma(
  title: [cdf 一定是 $N B V$ 的],
  id: "lem-02-random-variables-cdf-nbv",
  concepts: ("cdf-nbv",),
  depends: (),
  aliases: ("cdf 一定是 NBV 的",),
)[
任意的 random variable 的 cdf $F_X$ 都是一个 $N B V$ function.

]
#proof[
依旧见 notes, 有一个关键 lemma: $F in B V$ 当且仅当它可以表示为两个
monotone increasing function 的差.
而 random variable 的 cdf $F_X$ 自身是一个 non-decreasing function, 因而首先 $F_X in B V$. \ 其次, 由 #ref(label("thm-02-random-variables-distribution-function")) 我们知道,
$F_X$ 是 right-continuous 的,
且 $F_X\(- oo\)= 0$. 因而 $F_X in N B V$.

]
因而我们自然得出:

#theorem(
  title: [一个 random variable 是 continuous random variable 的充要条件],
  id: "thm-02-random-variables-random-variable-continuous-random-variable",
  concepts: ("-random-variable-continuous-random-variable",),
  depends: (),
  aliases: ("一个 random variable 是 continuous random variable 的充要条件",),
)[
- 一个 random variable $X : Omega arrow.r bb(R)$ 的 cdf 一定是 $m$-a.e.
  differentiable 的.

- $X$ 是一个 continuous random variable 当且
  仅当 $bb(P)^X lt.double m$, 即当且仅当存在一个函数 $f_X : bb(R) arrow.r\[0\,oo\)$, 使得
  使得对于任意 Borel set $A subset.eq bb(R)$, 有 $ bb(P)^X\(A\)= integral_A f_X #h(0em) d m $
  这个函数 $f_X$ 即是:

  - #strong[distribution 对于 Lebesgue measure 的 Radon-Nikodym derivative]: $f_X = frac(d bb(P)^X, d m)$.

  - #strong[cdf $F_X$ 的 $m$-a.e.导数 $f_X = F'_X$.]

  我们也称这个 $f_X$ 是
  continuous random variable $X$ 的 #strong[probability density function (pdf).]

]
#proof[
即 remark 的最后一条结论. 由于 $F_X$ 是一个 $N B V$ function,
因而 $F_X$ 是 $m$-a.e. differentiable 的. \ 并且, $F_X in A C$ iff 它满足 FTC of Lebesgue integral.

]
#remark[
因而, 在简化的教材中, 通常会直接定义: 一个 random variable $X$
是 continuous random variable,
如果存在一个 $f_X$ 使得 $F_X\(x\)= integral_(- oo)^x f\(t\)#h(0em) d t$ for all $x$.
这里其实是跳过了我们刚才的所有步骤, 直接使用了这个等价条件. 因为这个条件也等价于:
$ F_X\(x\)= integral_(- oo)^x F'_X\(t\)#h(0em) d t quad forall x in bb(R) $

]
#definition(
  title: [probability density function (pdf)],
  id: "def-02-random-variables-probability-density-function-pdf",
  concepts: ("probability-density-function-pdf",),
  depends: (),
  aliases: ("probability density function (pdf)",),
)[
对于 continuous random variable $X$, 其 probability density function 定义为 $F_X$ 的 ($m$-a.e.)导数,
即
$ f_X\(x\):= F'_X\(x\)\,quad m upright("-a.e. ") x in bb(R) $

]
我们最后梳理一下.

- #strong[任意的 random variable] 的 cdf $F_X$ 都是一个 $N B V$ function, 因而#strong[一定 a.e. 可导].
  但是它的导数 $F'_X$ 的积分不一定返回原函数.

- #strong[如果一个 $m$-a.e. 导数 $F'_X$ 满足 $F_X\(x\)= integral_(- oo)^x F'_X\(t\)#h(0em) d t$
  对所有 $x in bb(R)$ 成立, 即导数的积分返回原函数, 那么 $X$ 就是一个 continuous random variable],
  而我们定义 $f_X := F'_X$ 为 $X$ 的 probability density function.

以及, 显然 pdf 有以下性质:

#proposition(
  title: [probability density function 的性质],
  id: "prop-02-random-variables-probability-density-function",
  concepts: ("probability-density-function",),
  depends: (),
  aliases: ("probability density function 的性质",),
)[
对于 continuous random variable $X$ with pdf $f_X$,

- $f_X\(x\)gt.eq 0$ for $m$-a.e. $x in bb(R)$. (因为 $F_X$ 是 non-decreasing 的.)

- $integral_(- oo)^(+ oo) f_X\(x\)#h(0em) d x = 1$. (因为 $F_X\(oo\)= 1$\.)

- 对于任意 Borel set $A$, 有 $ bb(P)\(X in A\)= bb(P)^X\(A\)= integral_A f_X\(x\)#h(0em) d x $

- 对于 $m$-a.e. $x in bb(R)$, $ f_X\(x\)= lim_(epsilon.alt arrow.r 0^(+)) frac(bb(P)^X\(\[x\,x + epsilon.alt\)\), epsilon.alt) = lim_(epsilon.alt arrow.r 0^(+)) frac(F_X\(x + epsilon.alt\)- F_X\(x\), epsilon.alt) $

]
=== singular continuous random variable 与 Lebesgue Decomposition Theorem
<singular-continuous-random-variable-与-lebesgue-decomposition-theorem>
对于 continuous random variable 的定义, 有些地方会简化定义为: continuous random variable 就是指其 cdf 是一个 continuous function.

但是我们现在知道, 这个定义是错的.
首先, 标准定义中的 absolutely continuous 要强于 continuous (它能推导出 a.e. differentiable);
而且, #strong[这个更强的定义是 necessary 的].

因为当提及 continuous random variable 时, 通常意思是它存在一个 pdf.
而存在一个 pdf 即意味着它满足 FTC of Lebesgue integral, 也就等价于 $F_X$ 一定是一个 absolutely continuous function.
而仅仅 continuous 什么都无法保证.

我们这里给出一个 counterexample: Cantor distribution. 它的 cdf 是 continuous 的, 但是它并没有能够满足 FTC of Lebesgue integral (返回原函数) 的 a.e. derivative,
因而没有 pdf.

#example(
  title: [\(#strong[Cantor distribution])],
  id: "ex-02-random-variables-cantor-distribution",
  concepts: ("cantor-distribution",),
  depends: (),
  aliases: ("(Cantor distribution)",),
)[
令 $X_n$ be 独立同分布 (i.i.d.) 的随机变量 $P\(X_n = 0\)= P\(X_n = 2\)= 1\/2$. 然后定义:
$ X := sum_(n = 1)^oo X_n / 3^n $
它刻画的是:

- 把 $\[0\,1\]$ 三等分, 去掉中间的部分, 然后在剩下的两部分中, 以 $1\/2$ 的概率选择左边的区间, 以 $1\/2$ 的概率选择右边的区间;

- 在选定的区间中, 再把它三等分, infinitely 重复这一过程.

- 最后, 这一行为会收敛于 Cantor set 上的一个点.

具体而言:

- 第 1 步 ($n = 1$) 我们查看 $X_1 / 3^1$,
  如果 $X_1 = 0$, 你选择了左边的区间 $\[0\,1\/3\]$\;
  如果 $X_1 = 2$, 你选择了右边的区间 $\[2\/3\,1\]$.

- 第 2 步 ($n = 2$): 在第 1 步选定的区间内，查看 $X_2 / 3^2 = X_2 / 9$
  如果 $X_2 = 0$, 你在当前小区间内选择了左侧的 1/3; 如果 $X_2 = 2$, 你在当前小区间内选择了右侧的 1/3.

- $dots.h.c$

从而, $X$ 的 range 是 Cantor set, recall:
这是一个 measure zero 的 uncountable set, 其 cardinality 是 continuum (与 $bb(R)$ 等势).
$ C = { x in\[0\,1\]divides x =\(0 . a_1 a_2 a_3 dots.h\)_3\,upright(" where ") a_i in { 0\,2 } } $
它也表示了: 三进制小数中, 所有完全不包含数字 1 的小数的集合.

由于其 uncountability, 对于任意单点 $x$ 都有 $bb(P)\(X = x\)= 0$, #strong[因而 $F_X$ 在 $bb(R)$ 上处处连续]\;
并且容易证明: #strong[$F_X$ 在 $x$ 处的导数 $F'_X\(x\)= 0$]. (因为对于 $C^c$ 中的任意被挖掉的区间,
$F_X$ 在这个区间上是 constant 的).

然而, $F'_X = 0$ 却#strong[不满足 FTC of Lebesgue integral]. 比如反例: $F_X\(1\)= 1$,
但是 $ integral_(- oo)^1 F'_X\(t\)#h(0em) d t = 0 $
因而 $X$ 没有 pdf, 也就不是 continuous random variable.

]
对于 Cantor distribution 这个例子, 我们称这样的 random variable 是一个 #strong[singular continuous random variable]:

#definition(
  title: [singular continuous random variable],
  id: "def-02-random-variables-singular-continuous-random-variable",
  concepts: ("singular-continuous-random-variable",),
  depends: (),
  aliases: ("singular continuous random variable",),
)[
对于 random variable $X : Omega arrow.r bb(R)$,
如果 $X$ 的 cdf $F_X$ 是一个 continuous function,
并且 $bb(P)^X tack.t m$ (即存在一个 measure zero 的 Borel set $N$ 使得 $bb(P)^X\(N\)= 1$, 也等价于
$F_X$ 的导数 $F'_X = 0$ a.e.), 那么我们称 $X$ 是一个 singular continuous random variable.

]
#remark[
singular continuous random variable 的意思是, 在 $bb(R)$ 上, $X$ 的值 a.s.
落在一个 measure zero 的 set 上, 也就是说它的 cdf 大部分是平的,
只有在 measure zero 的 set 上才有 jump.

]
这个例子向我们说明了: 除了 discrete random variable 和 continuous random variable 以外,
还有其他的奇异的 random variables. 而下面这一定理刻画了任意的 random variable 的结构:

#theorem(
  title: [Lebesgue Decomposition Theorem],
  id: "thm-02-random-variables-lebesgue-decomposition-theorem",
  concepts: ("lebesgue-decomposition-theorem",),
  depends: (),
  aliases: ("Lebesgue Decomposition Theorem",),
)[
对于任意 random variable $X : Omega arrow.r bb(R)$,
其 distribution $bb(P)^X$ 可以唯一分解为三个 mutually singular 的 measure 的和:
$ bb(P)^X = bb(P)_(a c)^X + bb(P)_(s c)^X + bb(P)_d^X $
其中 $bb(P)_(a c)^X lt.double m$ 是 absolutely continuous measure,
$bb(P)_(s c)^X perp m$ 是一个 singular continuous measure,
$bb(P)_d^X perp m$ 是 discrete measure.

]
#proof[
TODO.

]
#remark[
我们也可以这样展开:
$ F_X\(x\)= integral_(- oo)^x f_(a c)\(t\)thin d t + sum_(x_i lt.eq x) p_d\(x_i\)+ F_(s c)\(x\) $
其中 $f_(a c)$ 是 $X_(a c)$ 的 pdf, $p_d$ 是 $X_d$ 的 pmf, 而 $F_(s c)$ 由于其奇异性是无法分解的.

]
== expectation and variance
<expectation-and-variance>
Distribution 是一个 random variable 的完整刻画, 而这一节我们来谈一谈 expectation
和 variance, 这是一个 random variable 的两个重要的数值特征: 它的均值和离散程度.

最后我们会谈一谈#strong[$L^2\(Omega\,cal(F)\,bb(P)\)$ 空间]:
all square-integrable random variables; 以及它的一个重要 subspace
$L_0^2\(Omega\,cal(F)\,bb(P)\)$:
所有 square-integrable 的 zero-centered random variables.
它们都是由 random variables 组成的 Hilbert space, 并且在其中,
expectation, variance, covariance 都会得到一个非常自然的 interpretation,
展现这个空间的几何结构.

=== expectation and variance 的 definition 和计算方法
<expectation-and-variance-的-definition-和计算方法>
随机变量的 #strong[expectation] 是它 w.r.t. 它所在概率空间 prob measure $bb(P)$ 的积分,
表示它的值的 prob-weighted average;

而其 #strong[variance] 是 $\(X - E\(X\)\)^2$ 这个 induced RV w.r.t. $bb(P)$ 的积分,
表示 $X$ 离它的值的 weighted average $bb(E)\(X\)$的聚集程度:

#definition(
  title: [expectation and variance of random variable],
  id: "def-02-random-variables-expectation-and-variance-of-random-variable",
  concepts: ("expectation-and-variance-of-random-variable",),
  depends: (),
  aliases: ("expectation and variance of random variable",),
)[
对于 random variable $X : Omega arrow.r bb(R)$,
其 expectation 定义为
$ bb(E)\[X\]:= integral_Omega X #h(0em) d bb(P) $
其 variance 定义为
$ upright("Var")\(X\):= bb(E)\[\(X - bb(E)\[X\]\)^2\]= integral_Omega\(X - bb(E)\[X\]\)^2#h(0em) d bb(P) $

]
#remark[
$integral_Omega d bb(P) = bb(P)\(Omega\)= 1$, 因而
$bb(E)\[X\]$ 可以看作是 $X$ 的值的 weighted average,
其中权重就是每个 sample point 在这个原 prob space 上的概率.

Note that: $bb(E)\[X\]$ 未必是 finite 的. $bb(E)\[X\]< oo arrow.l.r.double X in L^1\(bb(P)\)$.
$upright("Var")\(X\)< oo arrow.l.r.double X in L^2\(bb(P)\)$

]
要计算 discrete random vairable 的 expectation 和 variance, 直接 by def, sum 就可以:

#proposition(
  title: [discrete random variable 的 expectation 和 variance],
  id: "prop-02-random-variables-discrete-random-variable-expectation-variance",
  concepts: ("discrete-random-variable-expectation-variance",),
  depends: (),
  aliases: ("discrete random variable 的 expectation 和 variance",),
)[
对于 discrete random variable $X$ with pmf $p_X$,
$ bb(E)\[X\]= sum_x x p_X\(x\)\,quad upright("Var")\(X\)= sum_x\(x - bb(E)\[X\]\)^2p_X\(x\) $

]
非常简单.

但是对于 continuous random variable 而言, 怎么求呢? 这里有一个 w.r.t. prob measure $bb(P)$ 的积分,
有点难计算. 我们更希望计算 w.r.t. Lebesgue measure $m$ 的积分,
这样就可以用一些经典的方法来算它了.

为了实现这个目标, 我们首先需要一个工具来过渡一下:

#lemma(
  title: [用 distribution ($X$ 的 push-forward measure) 计算 expectation],
  id: "lem-02-random-variables-distribution-x-push-forward-measure-expectation",
  concepts: ("-distribution-x-push-forward-measure-expectation",),
  depends: (),
  aliases: ("用 distribution (X 的 push-forward measure) 计算 expectation",),
)[
对于 random variable $X : Omega arrow.r bb(R)$, 如果 $X$ integrable, 那么其 expectation
$ bb(E)\[X\]= integral_(bb(R)) x #h(0em) d bb(P)^X\(x\) $

]
#proof[
这个结论是 Lebesgue integral 的 change of variable formula 的一个 special case.
注意, $X = upright("id") compose X$ ($upright("id") : bb(R) arrow.r bb(R)$ 是恒等函数).

By change of variable formula,
$ integral_Omega X #h(0em) d bb(P) = integral_Omega\(upright("id") compose X\)#h(0em) d bb(P) = integral_(bb(R)) upright("id")\(x\)#h(0em) d bb(P)^X\(x\)= integral_(bb(R)) x #h(0em) d bb(P)^X\(x\) $
(如果不用 change of variable theorem, 也可以证明. 考虑 simple function 的 case, 显然;
然后对 simple function 自然成立, 然后用 monotone convergence theorem 推广到一般情况.)

\/\/TODO: 从 diffeomorphism version 的 change of variable formula 证明 push-forward version
的 change of variable formula, 然后 apply 这个结论.
参考: #link("https://en.wikipedia.org/wiki/Change_of_variables")[change of variable]

]
#proposition(
  title: [continuous random variable 的 expectation 和 variance],
  id: "prop-02-random-variables-continuous-random-variable-expectation-variance",
  concepts: ("continuous-random-variable-expectation-variance",),
  depends: (),
  aliases: ("continuous random variable 的 expectation 和 variance",),
)[
对于 continuous random variable $X$ with pdf $f_X$, 如果 $bb(E)\[X\]$ 和 $upright("Var")\(X\)$ 都是 finite 的, 那么
$ bb(E)\[X\]= integral_(- oo)^(+ oo) x f_X\(x\)#h(0em) d x\,quad upright("Var")\(X\)= integral_(- oo)^(+ oo)\(x - bb(E)\[X\]\)^2f_X\(x\)#h(0em) d x $
并且, 对于任意的 measurable function $g : bb(R) arrow.r bb(R)$, 都有
$ bb(E)\[g\(X\)\]= integral_(- oo)^(+ oo) g\(x\)f_X\(x\)#h(0em) d x $

]
#proof[
由于 $bb(E)\[X\]= integral_(bb(R)) x #h(0em) d bb(P)^X\(x\)$, 而对于 ctn random variable, $ d bb(P)^X\(x\)= f_X\(x\)#h(0em) d lambda\(x\) $
从而得证.

]
#proposition(
  title: [expectation 的性质],
  id: "prop-02-random-variables-expectation",
  concepts: ("expectation",),
  depends: (),
  aliases: ("expectation 的性质",),
)[
令 $X\,Y : Omega arrow.r bb(R)$ 为 #strong[integrable] random variables, 则

- #strong[linearity of expectation]: $bb(E)\[a X + b Y\]= a bb(E)\[X\]+ b bb(E)\[Y\]$ for any $a\,b in bb(R)$.

- #strong[monotonicity of expectation]: 如果 $X lt.eq Y$ a.s., 那么 $bb(E)\[X\]lt.eq bb(E)\[Y\]$.

- #strong[absolute value]: $bb(E)\[X\]lt.eq bb(E)\[\|X\|\]$

]
这三条性质都容易验证, 直接 follow from linearity of Lebesgue integral,
monotonicity of Lebesgue integral, triangle inequality of Lebesgue integral.

#proposition(
  title: [computing variance],
  id: "prop-02-random-variables-computing-variance",
  concepts: ("computing-variance",),
  depends: (),
  aliases: ("computing variance",),
)[
对于 random variable $X$ with finite expectation,
$ upright("Var")\(X\)= bb(E)\[X^2\]-\(bb(E)\[X\]\)^2 $

]
By def, 容易验证.

=== $L_0^2\(Omega\,cal(F)\,bb(P)\)$ 与 covariance and correlation as inner product and cosine
<l_02omega-mathcalf-mathbbp-与-covariance-and-correlation-as-inner-product-and-cosine>
我们 recall measure theory 中的一丢丢 functional analysis 的内容:
$ L^2\(Omega\,cal(F)\,bb(P)\)= { X : Omega arrow.r bb(R) divides X upright(" is measurable(即 RV)) and ") bb(E)\[X^2\]< oo }\/tilde.op $
where $tilde.op$ 表示 almost sure equality 的等价类, 即
$ X tilde.op Y arrow.l.r.double bb(P)\({ omega in Omega : X\(omega\)= Y\(omega\)}\)= 1 $
即把所有 a.s. 相等的 random variables 都看作相等.

我们知道, 这是一个 #strong[Hilbert space], 即一个 complete inner product space, 其中

- 两个 random variables as vectors 的 inner product 定义为:
  $chevron.l X\,Y chevron.r := bb(E)\[X Y\]$ 即它们的 second

- 一个 random variable 的 norm 即:
  $parallel X parallel := sqrt(chevron.l X\,X chevron.r) = sqrt(bb(E)\[X^2\])$ 即它的 second moment 的 square root.
  它表示了这个 random variable 的整体离散程度.

虽然这个空间已经有一定的 information geometry 了, 但是我们实际上希望能够
用一个结构来描述两个 random variables 之间的线性相关性:

- 任意取一个 $omega$, $X\(omega\)$ 较大 (距离它的 expectation 较远) 的时候,
  $Y\(omega\)$ 是否也通常较大 (距离它的 expectation 较远)?
  $X\(omega\)$ 较小的时候, $Y\(omega\)$ 是否也通常较小?

而 $L^2\(Omega\,cal(F)\,bb(P)\)$ 这个空间作为一个 Hilbert space 时, 两个
random variables 之间的距离其实是它们作为函数的相似性而不是它们变化趋势 (波动) 的相似性.

比如考虑 $X = x$ 和 $Y = x + 5$, 它们的线性相关性其实是 1, 即变化趋势完全相同, 但是
它们在 $L^2\(\[0\,4\]\,cal(F)\,bb(P)\)$ 中的 cosine similarity 却是
$ frac(chevron.l X\,Y chevron.r, parallel X parallel parallel Y parallel) = frac(46\/3, sqrt(\(16\/3\)\(151\/3\))) = 46 / sqrt(2416) approx 0.936 $
我们希望的是这个 cosine similarity 应当是 1.
即, 应该忽略掉绝对数值, 而是考虑这两个 random variables 的变化趋势.

因而 solution: normalize 每个 random variable, 把它们移动到
均值为 0 的位置! 即: 把每个 $X$ center 为 $X - bb(E)\[X\]$. 这就是:

#definition(
  title: [zero-centered square integrable random variables
$L_0^2\(Omega\,cal(F)\,bb(P)\)$],
  id: "def-02-random-variables-zero-centered-square-integrable-random-variables-l-2-0-omega-mat",
  concepts: ("zero-centered-square-integrable-random-variables-l-2-0-omega-mat",),
  depends: (),
  aliases: ("zero-centered square integrable random variables L^2_0(\\Omega, \\mathcal{F}, \\mathbb{P})",),
)[
我们定义:
$ L_0^2\(Omega\,cal(F)\,bb(P)\):= { X in L^2\(Omega\,cal(F)\,bb(P)\)divides bb(E)\[X\]= 0 } $
注意, 这个空间是 $L^2\(Omega\,cal(F)\,bb(P)\)$ 的一个 subspace.

]
并且, #strong[我们可以通过把每个 $X$ center 为 $X - bb(E)\[X\]$ 的行为,
把 $X$ 从 $L^2\(Omega\,cal(F)\,bb(P)\)$ 投影到
$L_0^2\(Omega\,cal(F)\,bb(P)\)$ 这个 subspace 上.] \ 而投影+度量的行为, 就是计算:

#definition(
  title: [covariance],
  id: "def-02-random-variables-covariance",
  concepts: ("covariance",),
  depends: (),
  aliases: ("covariance",),
)[
给定两个 random variables $X\,Y$, 我们定义它们的 covariance 为
$ upright("Cov")\(X\,Y\):= bb(E)\[\(X - bb(E)\[X\]\)\(Y - bb(E)\[Y\]\)\]= bb(E)\[X Y\]- bb(E)\[X\]bb(E)\[Y\] $

]
#remark[
Geometric intuition of covariance:
考虑取这两个 random variables 的一些 sample points 并分别作为 $\(x\,y\)$ 坐标.

- 如果它们的 covariance 是正的, 那么这些 sample points 倾向于拟合为一个斜率为正的 tendency line;

- 如果它们的 covariance 是负的, 那么这些 sample points 倾向于拟合为一个斜率为负的 tendency line;

- 如果它们的 covariance 是 0, 那么这些 sample points 倾向于拟合为一个水平的 tendency line.

#diagram(
  prob-02-random-variables-diagram-01,
  id: "fig-prob-02-random-variables-diagram-01",
  caption: [正、负与零协方差对应的线性趋势],
  alt: "Three scatterplots with positive, negative, and zero linear covariance trends.",
)
但是注意:

- covariance 只捕捉 linear relationship, 即趋势是否呈直线,
  不过不能捕捉 nonlinear relationship. 之后在学习 independence 的时候,
  我们会知道即便 covariance 为 0, $X$ 和 $Y$ 仍然可能是 dependent 的.
  比如, 如果 $\(X\,Y\)$ 的联合分布 as a graph 是个圆圈, 那么 covariance
  就是 0, 但显然这两个变量之间是有关系的.

  #diagram(
    prob-02-random-variables-diagram-02,
    id: "fig-prob-02-random-variables-diagram-02",
    caption: [零协方差但不独立的圆周分布],
    alt: "Points on a circle show dependent variables whose covariance is zero.",
  )

- Covariance 的数值还包括了这两个 random variables 的 scale,
  因而还不能直接用来比较不同 random variables
  之间的 linear relationship 的强弱程度. 真正公平的
  linear relationship 还需要 normalize by norms,
  把这个关系定位到 $\[- 1\,1\]$ 的区间上 即等下定义的 correlation.

]
我们容易发现一件事情:

#theorem(
  title: [covariance 是一个 a positive semi-definite symmetric bilinear form],
  id: "thm-02-random-variables-covariance-a-positive-semi-definite-symmetric-bilinear-f",
  concepts: ("covariance-a-positive-semi-definite-symmetric-bilinear-f",),
  depends: (),
  aliases: ("covariance 是一个 a positive semi-definite symmetric bilinear form",),
)[
- covariance 是一个 #strong[symmetric bilinear form] (并且 #strong[translation-invariant], 忽略 translation) 的 operator:
  $ upright("Cov")\(a X + b\,c Y + d\)= a c thin upright("Cov")\(X\,Y\) $
  $ upright("Cov")\(X\,Y\)= upright("Cov")\(Y\,X\) $
  $ upright("Cov")\(X + Y\,Z\)= upright("Cov")\(X\,Z\)+ upright("Cov")\(Y\,Z\) $

- covariance 满足 positive definiteness: $upright("Cov")\(X\,X\)= upright("Var")\(X\)gt.eq 0$.

]
#proof[
By def.

]
而当我们把空间限定在 $L_0^2\(Omega\,cal(F)\,bb(P)\)$ 上时,

#theorem(
  title: [$L_0^2\(Omega\,cal(F)\,bb(P)\)$ 为一个 Hilbert space, with covariance as
an inner product],
  id: "thm-02-random-variables-l-2-0-omega-mathcal-f-mathbb-p-hilbert-space-with-covar",
  concepts: ("l-2-0-omega-mathcal-f-mathbb-p-hilbert-space-with-covar",),
  depends: (),
  aliases: ("L^2_0(\\Omega, \\mathcal{F}, \\mathbb{P}) 为一个 Hilbert space, with covariance as an inner product",),
)[
$#scale(x: 120%, y: 120%)[\(] L_0^2\(Omega\,cal(F)\,bb(P)\)\,chevron.l dot.op\,dot.op chevron.r_(upright("Cov")) #scale(x: 120%, y: 120%)[\)]$ 为一个 Hilbert space,
即: covariance 在其上是一个 inner product (positive definite symmetric bilinear form).

]
#proof[
很显然. 因为在 $L^2$ space 上, 一个 constant random variable 的
variance 是 0, 但是它并不是一个零函数; 而在 $L_0^2$ space 上,
所有的 random variables 都是 zero-centered 的,
因而 constant random variable 就是零函数了.
从而 covariance 在 $L_0^2$ space 上是 positive definite 的, 从而是 inner product. \

]
而在 $L_0^2\(Omega\,cal(F)\,bb(P)\)$ 上,
两个 random variables $X\,Y$ 之间的夹角 $theta$ 的 cosine, 就是它们
真正的 linear relationship 的强弱程度, 因而我们把它叫做 correlation:

#definition(
  title: [correlation],
  id: "def-02-random-variables-correlation",
  concepts: ("correlation",),
  depends: (),
  aliases: ("correlation",),
)[
$ rho\(X\,Y\)= frac("Cov"\(upright(X)\,upright(Y)\), sqrt("Var"\(X\)) sqrt("Var"\(Y\))) $

]
显然, $ rho\(X\,Y\)= cos theta $
where $theta$ 是 $X\,Y$ 之间的夹角.
And we have: $ upright("Cov")\(X\,Y\)= sigma_X sigma_Y rho\(X\,Y\) $
从而有以下显然的结论:

#proposition(
  title: [properties of correlation],
  id: "prop-02-random-variables-properties-of-correlation",
  concepts: ("properties-of-correlation",),
  depends: (),
  aliases: ("properties of correlation",),
)[
- $rho\(X\,Y\)in\[- 1\,1\]$

- 如果 $rho\(X\,Y\)= 1$, 那么 $Y = a X + b$ for some $a > 0$ and $b$\; 如果
  $rho\(X\,Y\)= - 1$, 那么 $Y = a X + b$ for some $a < 0$ and $b$\.~

- By Cauchy-Schwarz inequality, $\|upright("Cov")\(X\,Y\)\|lt.eq sigma_X sigma_Y$.

]
做一个总结:

#figure(
  align(center)[#table(
    columns: 3,
    align: (left,left,left,),
    table.header([], [#strong[$L^2$ space]], [#strong[$L_0^2$]],),
    table.hline(),
    [inner product $chevron.l X\,Y chevron.r$], [$bb(E)\[X Y\]$], [$"Cov"\(X\,Y\)$ (covariance)],
    [norm $parallel X parallel$], [$sqrt(bb(E)\[X^2\])$], [$sqrt("Var"\(X\))$ (standard deviation)],
    [cosine similarity], [$frac(bb(E)\[X Y\], sqrt(bb(E)\[X^2\]) sqrt(bb(E)\[Y^2\]))$], [$frac("Cov"\(X\,Y\), sqrt("Var"\(X\)) sqrt("Var"\(Y\)))$ (correlation)],
  )]
  , kind: table
  )

#strong[求两个 random variables 之间的 correlation,
就是把它们都 center 到 zero-centered 的位置 (即投影到 $L_0^2$ space 上),
然后计算它们在 $L_0^2$ space 上的 cosine similarity.] \ 此时我们看到 decomposition of variance:

#proposition(
  title: [两个 random variables 之和的 variance],
  id: "prop-02-random-variables-random-variables-variance",
  concepts: ("-random-variables-variance",),
  depends: (),
  aliases: ("两个 random variables 之和的 variance",),
)[
两个 random variables 的和的 variance 可分解成 variances 和 covariance:
$ upright("Var")\(X + Y\)= upright("Var")\(X\)+ upright("Var")\(Y\)+ 2 upright("Cov")\(X\,Y\) $

]
#proof[
$ "Var"\(X + Y\)= bb(E) [\( X + Y \)^2] -\(bb(E)\[X + Y\]\)^2= bb(E) [X^2] -\(bb(E)\[X\]\)^2+ bb(E) [Y^2] -\(bb(E)\[Y\]\)^2+ 2\(bb(E)\[X Y\]- bb(E)\[X\]bb(E)\[Y\]\) $

]
#remark[
它其实这就是标准的 inner product space 上的向量平方公式:
$ parallel X + Y parallel_(L_0^2)^2 = parallel X parallel_(L_0^2)^2 + parallel Y parallel_(L_0^2)^2 + 2 chevron.l X\,Y chevron.r_(L_0^2) $

]
== discrete random variables
<discrete-random-variables>
Recall: discrete random variable 是指其 range a.s. 是 countable 的 random variable.
(存在一个 countable set $S subset.eq bb(R)$
使得 $bb(P)\(X in S\)= 1$)

discrete RV 的 probability mass unction (pmf):
$ p_X\(x\):= bb(P)\(X = x\)\,quad forall x in bb(R) $
就是 $X$ 的 distribution $P^X$ 对于 counting measure of range $S$
的 Radon-Nikodym derivative:
$ p_X = frac(d bb(P)^X, d mu_(upright("S"))) $

因为假设 $X$ 的 range 是 $S = { x_1\,x_2\,dots.h }$,
那么对于任意 Borel set $B$,
$ bb(P)^X\(B\)= sum_(x_i in B) bb(P)\(X = x_i\)= sum_(x_i in B inter S) p_X\(x_i\)= integral_A p_X\(x\)#h(0em) d mu_(upright("S"))\(x\) $

下面我们给出一些经典的 discrete random variable 的例子, 以及它们的 pmf 和 cdf.

=== Bernoulli distribution and Binomial distribution
<bernoulli-distribution-and-binomial-distribution>
#example(
  title: [\(#strong[Bernoulli distribution])],
  id: "ex-02-random-variables-bernoulli-distribution",
  concepts: ("bernoulli-distribution",),
  depends: (),
  aliases: ("(Bernoulli distribution)",),
)[
令 $Omega := { omega_1\,omega_2 }$, $cal(F) := 2^Omega$. \ 令 $bb(P)\({ omega_1 }\)= p$, $bb(P)\({ omega_2 }\)= 1 - p$ 来表示这两个 singular 事件的概率. \ 令 $X\(omega_1\)= 1$, $X\(omega_2\)= 0$ 分别表示 success 和 failure. \ 那么显然可以计算:
$ bb(P)\(X = 0\)= bb(P)\({ omega_2 }\)= 1 - p\,quad bb(P)\(X = 1\)= bb(P)\({ omega_1 }\)= p $
我们称 $\(Omega\,cal(F)\,bb(P)\)$ 为一个 Bernoulli probability space
(它 model 了一个 Bernoulli trial, 即一个 random experiment with two possible outcomes: success 和 failure) \ 称 $X : Omega arrow.r { 0\,1 }$ 这个 random variable 为一个 #strong[Bernoulli random variable],
并称 $X$ 的 distribution $P^X$ 为一个 #strong[Bernoulli distribution], 写作
$ X tilde.op upright("Ber")\(p\) $
这是最简单的 random variable 和 distribution 了. 它 model 的是:
比如我们 toss 一枚 biased coin,
以 $p$ 的概率得到 heads (success),
以 $1 - p$ 的概率得到 tails (failure). \

]
#proposition(
  id: "prop-02-random-variables-proposition-010",
  concepts: ("proposition-010",),
  depends: (),
)[
如果 $X tilde.op upright("Ber")\(p\)$,
那么 $bb(E)\[X\]= p$, $upright("Var")\(X\)= p\(1 - p\)$.

]
显然.

#example(
  title: [\(#strong[Binomial distribution])],
  id: "ex-02-random-variables-binomial-distribution",
  concepts: ("binomial-distribution",),
  depends: (),
  aliases: ("(Binomial distribution)",),
)[
我们 independently repeat $n$ 次 Bernoulli trial,
每次 trial 的 success probability 都是 $p$. \ 考虑:
$ S := X_1 + X_2 + dots.h.c + X_n $ 为 success 的总次数. 那么 $S$ 是一个 discrete random variable
$S : Omega^n arrow.r bb(Z)_(gt.eq 0)$
容易计算出 $S$ 的 pmf:
$ p_S\(k\)= bb(P)\(S = k\)= binom(n, k) p^k\(1 - p\)^(n - k)\,quad k = 0\,1\,dots.h\,n $
我们称 $S$ 的 distribution $P^S$ 为一个 #strong[Binomial distribution], 写作
$ S tilde.op upright("Bin")\(n\,p\) $
它 model 的是: 比如我们 toss 一枚 biased coin $n$ 次,
得到 heads 的总次数. \

]
#proposition(
  id: "prop-02-random-variables-proposition-011",
  concepts: ("proposition-011",),
  depends: (),
)[
如果 $S tilde.op upright("Bin")\(n\,p\)$, 那么 $bb(E)\[S\]= n p$, $upright("Var")\(S\)= n p\(1 - p\)$.

]
#proof[
$ bb(E)\[X\]= sum_(k = 1)^n k dot.op bb(P)\(X = k\)= sum_(k = 1)^n k dot.op binom(n, k) p^k\(1 - p\)^(n - k)= p\(1 - p\)^(n - 1)sum_(k = 1)^n k dot.op binom(n, k)\(frac(p, 1 - p)\)^(k - 1) $
由于 $ \(1 + t\)^n= sum_(k = 0)^n binom(n, k) t^k arrow.r.double.long n\(1 + t\)^(n - 1)= sum_(k = 1)^n k dot.op binom(n, k) t^(k - 1) $
可以得到 $ bb(E)\[X\]= p\(1 - p\)^(n - 1)dot.op n\(1 + frac(p, 1 - p)\)^(n - 1)= n p $
然后计算得
$upright("Var")\(X\)= n p\(1 - p\)$. 但是这是比较麻烦的方法.
也可以利用 $X = sum_(i = 1)^n X_i$,
其中 $X_i tilde.op upright("Ber")\(p\)$ i.i.d 这个事实来计算, 那么直接通过
线性叠加 Bernoulli random variable 的 expectation 和 variance 就可以了.

]
=== Geometric distribution and Negative Binomial distribution
<geometric-distribution-and-negative-binomial-distribution>
#example(
  title: [\(#strong[Geometric distribution])],
  id: "ex-02-random-variables-geometric-distribution",
  concepts: ("geometric-distribution",),
  depends: (),
  aliases: ("(Geometric distribution)",),
)[
我们 perform independent Bernoulli trial, 每次 trial 的 success probability 都是 $p$. \ 考虑 random variable $T$ 表示第一次 success 发生的 trial number. (也就是等于: 我们一直 trial, 直到第一次 success 发生, 那么这个 trial 的 number 就是 $T$). \ 那么 $T$ 是一个 discrete random variable $T : Omega^oo arrow.r bb(Z)_(gt.eq 1)$. \ 容易计算出 $T$ 的 pmf:
$ p_T\(k\)= bb(P)\(T = k\)=\(1 - p\)^(k - 1)p\,quad k = 1\,2\,dots.h $
我们称 $T$ 的 distribution $P^T$ 为一个 #strong[Geometric distribution], 写作
$ T tilde.op upright("Geom")\(p\) $
它 model 的是: 比如我们 toss 一枚 biased coin,
第一次得到 heads 的 trial number. \

]
#proposition(
  id: "prop-02-random-variables-proposition-012",
  concepts: ("proposition-012",),
  depends: (),
)[
如果 $X tilde.op upright("Geom")\(p\)$, 那么 $bb(E)\[X\]= 1\/p$,
$upright("Var")\(X\)=\(1 - p\)\/p^2$.

]
#proof[
$ bb(E)\[X\]= sum_(k = 1)^oo k\(1 - p\)^(k - 1)p = p sum_(k = 1)^oo k\(1 - p\)^(k - 1)= p #scale(x: 120%, y: 120%)[\(] - frac(d, d\(1 - p\)) sum_(k = 0)^oo\(1 - p\)^k#scale(x: 120%, y: 120%)[\)] = - p - frac(d, d p) frac(1, 1 -\(1 - p\)) = 1 / p $
similarly, 可以计算得$ bb(E)\[X^2\]= frac(2 - p, p^2) $
因而 $ upright("Var")\[X\]= bb(E)\[X^2\]-\(bb(E)\[X\]\)^2= frac(1 - p, p^2) $

]
#example(
  title: [\(#strong[Negative Binomial distribution])],
  id: "ex-02-random-variables-negative-binomial-distribution",
  concepts: ("negative-binomial-distribution",),
  depends: (),
  aliases: ("(Negative Binomial distribution)",),
)[
这是 Geometric distribution 的 generalization (但不完全一样). \ 我们 perform independent Bernoulli trial,
每次 trial 的 success probability 都是 $p$. (即 independent and identically distributed) \ 令 random variable $T_r$ 表示第 $r$ 次 success 发生之前
的 failures 的数量.
(也就是等于: 我们一直 trial, 直到第
$r$ 次 success 发生, 那么这个 trial 的 number 就是 $T_r + r$,
因为 $T_r$ 是 failures 的数量, 还要加上 $r - 1$ 个 success.
). \ 那么 $T_r$ 是一个 discrete random variable
$T_r : Omega^oo arrow.r bb(Z)_(gt.eq 0)$. \ 容易计算出 $T_r$ 的 pmf:
$ p_(T_r)\(k\)= bb(P)\(T_r = k\)= binom(k + r - 1, k)\(1 - p\)^k p^r\,quad k = 0\,1\,2\,dots.h $
这是因为:最后一次 success 的位置是固定的. 我们要在前 $k + r - 1$ 次 trial
中选择 $k$ 次作为 failures. \ 我们称 $T_r$ 的 distribution $P^(T_r)$ 为一个 #strong[Negative Binomial distribution], 写作
$ T_r tilde.op upright("NB")\(r\,p\) $
它 model 的是: 比如我们 toss 一枚 biased coin,
得到第 $r$ 个 heads 之前会经历的 failures 的数量. \

]
=== Poisson distribution
<poisson-distribution>
#example(
  title: [\(#strong[Poisson distribution])],
  id: "ex-02-random-variables-poisson-distribution",
  concepts: ("poisson-distribution",),
  depends: (),
  aliases: ("(Poisson distribution)",),
)[
考虑这一 pmf:
$ bb(P)\(X = k\)= e^(- lambda) frac(lambda^k, k !)\,quad k = 0\,1\,2\,dots.h $
我们称 $X$ 的 distribution $P^X$ 为一个 #strong[Poisson distribution], 写作
$ X tilde.op upright("Poi")\(lambda\)\,quad lambda > 0 $
以 $lambda = 3$ 为例画出 pmf 示意图:

#diagram(
  prob-02-random-variables-diagram-03,
  id: "fig-prob-02-random-variables-diagram-03",
  caption: [参数 $lambda=3$ 的 Poisson 概率质量函数],
  alt: "A stem plot of the Poisson probability mass function with lambda equal to 3.",
)
#remark[
当 $n arrow.r oo$ 时,
$upright("Bin")\(n\,lambda\/n\)$ 的 distribution
趋近于 $upright("Poi")\(lambda\)$. \ 考虑 $X tilde.op B (n \, lambda / n)$, 对于固定的 $k$:
$ bb(P)\(X = k\)= binom(n, k) (lambda / n)^k (1 - lambda / n)^(n - k) $
展开组合数 $binom(n, k)$:
$ bb(P)\(X = k\)= frac(n\(n - 1\)dots.h\(n - k + 1\), k !) dot.op lambda^k / n^k dot.op (1 - lambda / n)^n dot.op (1 - lambda / n)^(- k) $
重组项:
$ bb(P)\(X = k\)= frac(lambda^k, k !) dot.op underbrace(frac(n\(n - 1\)dots.h\(n - k + 1\), n^k), \(1\)) dot.op underbrace((1 - lambda / n)^n, \(2\)) dot.op underbrace((1 - lambda / n)^(- k), \(3\)) $
其中, (1) 的 limit 是 1,
(2) 的 limit 是 $e^(- lambda)$, (3) 的 limit 是 1, 因而
$ lim_(n arrow.r oo) bb(P)\(X = k\)= e^(- lambda) frac(lambda^k, k !) $
这个极限行为的意义是:

- $lambda$ 表示: 在一个固定时间/空间窗口内, 一个事件出现的平均次数的观测.

- 我们把这段时间间分成 $n$ 个小窗口, 将这个观测作为先验知识用来 model 这类事件实现的平均概率, 那么
  每个小窗口内事件出现的概率是 $p = lambda\/n$.

- 每个 $upright("Bin")\(n\,lambda\/n\)$ 都表示: 在时间细分成
  $n$ 个小窗口的情况下, 这个事件出现的次数的分布. (注意不是在时间上的分布, 而是在次数上的分布)

- 当 $n arrow.r oo$ 时, 其意义: 基于连续时间的估计,
  这个事件在原固定事件窗口内出现的次数的分布. 这就是
  $upright("Poi")\(lambda\)$ 的意义.

因而 Poisson distribution 的意义本质上是:
#strong[给定对一个事件在固定窗口下出现的平均次数的观测(估计),
那么这个事件在这个窗口内出现 $n$ 次
($n = 0\,1\,2\,dots.h.c$)的概率是多少?] \ 所以 Poisson 分布, 即是#strong[根据一个事件在给定 windows 内发生次数的 expectation, 来估计这个事件在该 windows 内发生次数的分布的标准方法.] \

]
#remark[
Further remark: Poisson distribution 的用途.

- 它是 model \"大量级的小概率事件\" 的通用模型. \ 即一段时间内, 一件事情的发生的概率非常小 ($p lt.double 1$),
  但是有很多机会发生 ($n gt.double 1$). 比如放射性衰变.

- 现实世界中, 对于一些事情, 我们想要 model 其在一段时间内发生的总次数 ($n$) 和单次成功率 ($p$)
  是很困难的. 比如统计今天路过百货大楼的总人数 ($n$), 以及每个人路过百货大楼时走进去的概率 ($p$). 但是我们
  很容易可以知道: $lambda = n p$ 的观测. 即: 每天平均有多少人走进百货大楼. 那么我们就可以用 Poisson distribution 来 model 这件事情在一天内发生的次数的分布. \

]
]
#proposition(
  id: "prop-02-random-variables-proposition-013",
  concepts: ("proposition-013",),
  depends: (),
)[
如果 $X tilde.op upright("Poi")\(lambda\)$, 那么 $bb(E)\[X\]= lambda$, $upright("Var")\(X\)= lambda$.

]
#proof[
recall $e^x$ 的 taylor expansion: $ e^x = sum_(k = 0)^oo frac(x^k, k !) $
因而
$ bb(E)\[X\]= sum_(k = 0)^oo k e^(- lambda) frac(lambda^k, k !) = e^(- lambda) lambda sum_(k = 1)^oo frac(lambda^(k - 1), \(k - 1\)!) = e^(- lambda) lambda e^lambda = lambda $
similarly, 可以计算得 $ bb(E)\[X^2\]= lambda^2 + lambda $
因此, $ upright("Var")\(X\)= bb(E)\[X^2\]-\(bb(E)\[X\]\)^2= lambda $

]
==== Poisson distribution 的 additivity
<poisson-distribution-的-additivity>
#theorem(
  title: [additivity of Poisson distribution],
  id: "thm-02-random-variables-additivity-of-poisson-distribution",
  concepts: ("additivity-of-poisson-distribution",),
  depends: (),
  aliases: ("additivity of Poisson distribution",),
)[
如果 $X tilde.op upright("Poi")\(lambda_1\)$, $Y tilde.op upright("Poi")\(lambda_2\)$ are independent, 那么
$ X + Y tilde.op upright("Poi")\(lambda_1 + lambda_2\) $

]
#remark[
这个事实通过简单的计算即可得到.

但是值得一提的是, 我们之后会证明一个结论: 两个 independent 的 random variable
的 sum 的 distribution 是它们 convolution 的 distribution.

而 Poisson distribution 的 convolution 仍然是 Poisson distribution,
并且是 linear 的. 这就是 additivity of Poisson distribution 的本质原因.

]
== continuous random variables
<continuous-random-variables>
recall: 总而言之, continuous random variable 是指其 distribution $bb(P)^X$
对于 Lebesgue measure $m$ 是 absolutely continuous 的 random variable,
等价于存在一个 pdf $f_X$ 使得$ F_X\(x\)= integral_(- oo)^x f_X\(y\)d y $ 对于任意 $x$ 都成立.

而由 $bb(E)\[X\]= integral_Omega X d bb(P) = integral_(bb(R)) x d bb(P)^X = integral_(bb(R)) x f_X\(x\)d x$ 可得
$ bb(E)\[X\]= integral_(- oo)^(+ oo) x f_X\(x\)d x\,quad upright("Var")\(X\)= integral_(- oo)^(+ oo)\(x - bb(E)\[X\]\)^2f_X\(x\)d x $

这里还有一个额外的结论:

#proposition(
  id: "prop-02-random-variables-proposition-014",
  concepts: ("proposition-014",),
  depends: (),
)[
对于任意的 measurable function $g : bb(R) arrow.r bb(R)$, 都有
$ bb(E)\[g\(X\)\]= integral_(- oo)^(+ oo) g\(x\)f_X\(x\)d x $

]
#proof[
$ bb(E)\[g\(X\)\] & = integral_Omega g\(X\(w\)\)thin d bb(P)\(w\)\
 & = integral_Omega g compose X thin d bb(P)\
 & = integral_(bb(R)) g thin d bb(P)^X\
 & = integral_(- oo)^(+ oo) g\(x\)f_X\(x\)thin d x $

]
下面我们介绍一些常见的 continuous random variables, 以及它们的 pdf, cdf, expectation 和 variance.

=== uniform distribution: 最简单的 continuous RV
<uniform-distribution-最简单的-continuous-rv>
#definition(
  title: [uniform distribution],
  id: "def-02-random-variables-uniform-distribution",
  concepts: ("uniform-distribution",),
  depends: (),
  aliases: ("uniform distribution",),
)[
如果 $f_X\(x\)= frac(1, b - a)$ on $\(a\,b\)$ and $0$ elsewhere,
那么我们称 $X$ 的 distribution $P^X$ 为一个
#strong[uniform distribution], 写作
$ X tilde.op U\(\[a\,b\]\) $

]
对于 uniform distribution, 很容易计算得:
$ F_X\(x\)= frac(x - b, b - a)\,quad bb(E)\[X\]= frac(a + b, 2)\,quad upright("Var")\(X\)= frac(\(b - a\)^2, 12) $

#example(
  title: [\(uniform distribution 的 pdf 和 cdf)],
  id: "ex-02-random-variables-uniform-distribution-pdf-cdf",
  concepts: ("uniform-distribution-pdf-cdf",),
  depends: (),
  aliases: ("(uniform distribution 的 pdf 和 cdf)",),
)[
考虑 $X tilde.op U\(\[a\,b\]\)$, 其 pdf 和 cdf 的图像如下:

#diagram(
  prob-02-random-variables-diagram-04,
  id: "fig-prob-02-random-variables-diagram-04",
  caption: [区间 $[a,b]$ 上均匀分布的概率密度函数],
  alt: "The uniform density is constant at 1/(b-a) between a and b and zero outside.",
)
#diagram(
  prob-02-random-variables-diagram-05,
  id: "fig-prob-02-random-variables-diagram-05",
  caption: [区间 $[a,b]$ 上均匀分布的累积分布函数],
  alt: "The uniform cumulative distribution rises linearly from zero at a to one at b.",
)
]
=== exponential distribution: geometric distribution 的 continuous version
<exponential-distribution-geometric-distribution-的-continuous-version>
Exponential random variable model 的是一盏灯的 remaining lifetime.
它 assume: 任意时间, 这盏灯有一个 constant 的磨损速率.

假设它的磨损速率是 $lambda = lambda_X\(t\)$ for all $t$,
那么在任意时间 $t$ 上:
$ lambda_X\(t\)= lim_(h arrow.r 0^(+)) frac(P\(X in\(t\,t + h\]\), h) = lim_(h arrow.r 0^(+)) frac(bb(P)\(t lt.eq X lt.eq t + h\), h) dot.op frac(1, bb(P)\(X > t\)) = frac(f_X\(t\), 1 - F_X\(t\)) $

即 ODE:
$ lambda = frac(F'_X\(t\), 1 - F_X\(t\)) $
with initial condition $F_X\(0\)= 0$.

我们知道这个 ODE 的 solution 是: $ F_X\(t\)= {1 - e^(- lambda t)\,quad t > 0\
0\,quad t lt.eq 0\,quad f_X\(t\)= {lambda e^(- lambda t)\,quad t > 0\
0\,quad t lt.eq 0 $

#definition(
  title: [exponential distribution],
  id: "def-02-random-variables-exponential-distribution",
  concepts: ("exponential-distribution",),
  depends: (),
  aliases: ("exponential distribution",),
)[
我们称 $X$ 为一个 #strong[exponential random variable] with parameter $lambda$,
如果它的 pdf is given by: $ f\(x\)= {lambda e^(- lambda x)\,quad x > 0\
0\,quad x lt.eq 0 $
写作$ X tilde.op upright("Exp")\(lambda\) $

]
刚才已经计算出, exponential random variable 的
distribution 为$ F_X\(x\)= {integral_(- oo)^x f\(t\)#h(0em) d t = lambda integral_0^x e^(- lambda t) #h(0em) d t = 1 - e^(- lambda x)\,quad x > 0\
0\,quad x < 0 $
容易验证, $F_X\(x\)= 0$ when $x arrow.r - oo$, 以及 $F_X\(x\)arrow.r 1$ when $x arrow.r oo$

计算其 expectation:
$ bb(E)\[X^n\] & = lambda integral_0^oo x^n e^(- lambda x) #h(0em) d x\
 & = - integral_0^oo x^n\(e^(- lambda x)\)'#h(0em) d x\
 & = 0 + integral_0^oo n x^(n - 1) e^(- lambda x) #h(0em) d x\
 & = n / lambda bb(E)\(X^(n - 1)\) $
并 notice: $bb(E)\[X^0\]= bb(E)\[1\]= 1$.
因而 recursively get: $ bb(E)\[X^n\]= frac(n !, lambda^n) $
即:
$bb(E)\[X\]= 1 / lambda\,bb(E)\[X^2\]= 2 / lambda^2\,dots.h.c$
从而: $ V a r\[X\]= 2 / lambda^2 - 1 / lambda^2 = 1 / lambda^2 $

#diagram(
  prob-02-random-variables-diagram-06,
  id: "fig-prob-02-random-variables-diagram-06",
  caption: [指数分布的概率密度函数],
  alt: "The exponential density decreases from lambda toward zero as x increases.",
)
#diagram(
  prob-02-random-variables-diagram-07,
  id: "fig-prob-02-random-variables-diagram-07",
  caption: [指数分布的累积分布函数],
  alt: "The exponential cumulative distribution rises from zero toward one.",
)
#remark[
exponential 随机变量是 geometric 随机变量的 continuous analogue.
因为 geometric random variable 是假设一个事件在
每个时间点以 constant 的概率发生,
用来 model 它第一次发生的时间;

而 exponential random variable 其实也是, 只是 on a continuous
time scale:
它假设的 constant 损坏率其实 implies:
#strong[在任意时间, 如果灯还没坏, 那么灯此刻坏掉的概率是 constant 的.]

#theorem(
  title: [memoryless property of exponential distribution],
  id: "thm-02-random-variables-memoryless-property-of-exponential-distribution",
  concepts: ("memoryless-property-of-exponential-distribution",),
  depends: (),
  aliases: ("memoryless property of exponential distribution",),
)[
任意 continuous RV, $ bb(P)\(X > b + t divides X > b\)= bb(P)\(X > t\)arrow.l.r.double X upright(" is an exponential random variable") $

]
#proof[
简单而言
$  & P\(X > b + t divides X > b\)= P\(X > t\)\
arrow.l.r.double & P\(X > b + t\)= P\(X > t\)P\(X > b\)\
arrow.l.r.double & X upright(" exponential") $

]
因而对于 geometric RV 的 pmf, 当我们把时间间隔 (discrete time interval) 变得越来越小,
这一行为的极限就变为了 exponential RV 的 pdf.

这是一个很自然的 limit behavior, 此处不验证了.

]
#example(
  id: "ex-02-random-variables-example-011",
  concepts: ("example-011",),
  depends: (),
)[
假设我们有一个 storage battery, 它的 lifetime 是 exponentially distributed 的, 并且 average 为 10 hours. Suppose 我们想要 use this battery for 5 hours for.

计算: probability of finishing the task, if: \ (a) 使用一个 new battery \ (b) 使用一个已经用过 2 hours 的 battery \

]
#solution[
$ bb(E)\[X\]= 10 = 1 / lambda arrow.r.double.long lambda = 1 / 10 $
如果我们使用一个 new battery, 则 want: $P\(X > 5\)= 1 - P\(X < 5\)= 1 - F_X\(5\)= e^(- 1 / 2)$
如果我们使用一个用过 2 hours 的 battery, 则 want: $ P\(X > 5 + 2 divides X > 2\)= e^(-\(5 + 2\)lambda) / e^(- 2 lambda) = e^(- 5 lambda) = = e^(- 1 / 2) $
Notice: $ P\(X > 5\)= P\(X > 5 + 2 divides X > 2\) $

]

=== Gamma distribution: negative binomial distribution 的 continuous version
<gamma-distribution-negative-binomial-distribution-的-continuous-version>
recall Gamma 函数:
$ Gamma\(alpha\)= integral_0^oo x^(alpha - 1) e^(- x) #h(0em) d x $
这个函数有一个重要的性质: $ Gamma\(alpha + 1\)= alpha Gamma\(alpha\) $
因而对于 $n in bb(N)$, 我们有: $ Gamma\(n\)=\(n - 1\)! $
Gamma 函数就是 factorial 函数的 continuous generalization.

#definition(
  title: [$Gamma$-distribution],
  id: "def-02-random-variables-gamma-distribution",
  concepts: ("gamma-distribution",),
  depends: (),
  aliases: ("\\Gamma-distribution",),
)[
如果 continuous random variable $X$ 的 pdf 是:
$ f_X\(x\)= cases(delim: "{", frac(lambda^alpha, Gamma\(alpha\)) x^(alpha - 1) e^(- lambda x)\, & x > 0\,, 0\, & x lt.eq 0) $
那么我们称 $X$ 服从 #strong[$Gamma$ distribution], 写作$ X tilde.op Gamma\(alpha\,lambda\) $
其中 $alpha > 0$ 称为 shape parameter, $lambda > 0$ 称为 rate parameter.

]
$Gamma$ distribution 的 cdf 这样求: for $a gt.eq 0$,
$ F_X\(a\)= integral_(- oo)^a f_X\(x\)#h(0em) d x & = integral_0^a frac(lambda^alpha, Gamma\(alpha\)) x^(alpha - 1) e^(- lambda x) #h(0em) d x\
 & = frac(1, Gamma\(alpha\)) integral_0^(lambda a) t^(alpha - 1) e^(- t) #h(0em) d t $
and for $a < 0$, $F_X\(a\)= 0$.

Expectation:
$ bb(E)\[X\] & = frac(1, Gamma\(alpha\)) integral_0^oo\(lambda x\)^(alpha - 1)lambda e^(- lambda x) #h(0em) d x\
 & = frac(1, lambda Gamma\(alpha\)) integral_0^oo x^alpha e^(- x) #h(0em) d x\
 & = frac(Gamma\(alpha + 1\), lambda Gamma\(alpha\)) = alpha / lambda $
(since $Gamma\(alpha + 1\)= alpha Gamma\(alpha\)$\.)
同理我们可以计算得: $bb(E)\[X^2\]= frac(alpha\(alpha + 1\), lambda^2)$
从而 $ upright("Var")\[X\]= bb(E)\[X^2\]-\(bb(E)\[X\]\)^2= frac(alpha\(alpha + 1\), lambda^2) - alpha^2 / lambda^2 = alpha / lambda^2 $

容易发现: 当 $alpha = 1$ 时, $Gamma$ distribution 就退化成了 exponential distribution.
$ Gamma\(1\,lambda\)= upright("Exp")\(lambda\) $
而当 $alpha$ 是一个正整数 $n$ 时, $Gamma$ distribution 实际就是 $n$ 个
independent exponential distribution 的 sum:

#proposition(
  title: [Gamma distribution 即是 independent exponential distribution 的 sum],
  id: "prop-02-random-variables-gamma-distribution-independent-exponential-distribution-su",
  concepts: ("gamma-distribution-independent-exponential-distribution-su",),
  depends: (),
  aliases: ("Gamma distribution 即是 independent exponential distribution 的 sum",),
)[
Let $X_1\,X_2\,dots.h.c\,X_n tilde.op upright("Exp")\(lambda\)$ be i.i.d., 则
$ Gamma\(n\,lambda\)= sum_(i = 1)^n X_i $

]
#proof[
证明这一结论除了硬算之外, 更快的方法是通过 moment generating function.
\/\/TODO

]
#remark[
Gamma distribution 即多个 i.i.d. exponential distribution 的 sum; 而我们知道
exponential distribution 是 geometric distribution 的 continuous analogue;
因而 #strong[Gamma distribution 也是 negative binomial distribution 的 continuous analogue.]

考虑固定 rate parameter $lambda = 1$，不同 shape parameter $alpha$ 的 Gamma distribution：

#diagram(
  prob-02-random-variables-diagram-08,
  id: "fig-prob-02-random-variables-diagram-08",
  caption: [固定 $lambda=1$ 时不同 shape 参数的 Gamma 密度],
  alt: "Gamma density curves for alpha 1, 2, 3, and 5 with lambda fixed at 1.",
)

#diagram(
  prob-02-random-variables-diagram-09,
  id: "fig-prob-02-random-variables-diagram-09",
  caption: [固定 $lambda=1$ 时不同 shape 参数的 Gamma 分布函数],
  alt: "Gamma cumulative distribution curves for alpha 1, 2, 3, and 5 with lambda fixed at 1.",
)

- 当 $alpha = 1$ 时, Gamma 分布退化为指数分布, pdf 单调递减;

- 随着 $alpha$ 增大, pdf 从 0 处开始上升, 形成驼峰形状, 并逐渐向右平移;

- cdf 随 $alpha$ 增大而上升变缓, 表示分布的右尾变长。

]
=== normal random variables: 最重要的 continuous RV, 任意 RV 的叠加极限
<normal-random-variables-最重要的-continuous-rv-任意-rv-的叠加极限>
#definition(
  id: "def-02-random-variables-definition-017",
  concepts: ("definition-017",),
  depends: (),
)[
我们称 $X$ is #strong[normally distributed with parameter $mu$ and $sigma$], if the pdf of $X$ is given by: $ p\(x\)= frac(1, sigma sqrt(2 pi)) e^(- frac(\(x - mu\)^2, 2 sigma^2)) $
写作: $ X tilde.op cal(N)\(mu\,sigma^2\) $
特别地, 当 $mu = 0\,sigma = 1$ 时, $ X tilde.op cal(N)\(0\,1\) $被称为 #strong[standard normal distribution.]

]
- 验证其为 valid pdf:

  我们首先验证 standard normal distribution. 令:

  $ I := integral_0^oo e^(frac(- y^2, 2)) #h(0em) d y $
  则
  $ I^2 & = integral_0^oo e^(frac(- y^2, 2)) #h(0em) d y dot.op integral_0^oo e^(frac(- x^2, 2)) #h(0em) d x\
   & = integral_(bb(R)_(gt.eq 0)^2) e^(- frac(x^2 + y^2, 2)) #h(0em) d x thin d y\
   & = integral_0^(pi\/2) integral_0^oo e^(- r^2 / 2) r #h(0em) d r thin d theta\
   & = integral_0^(pi\/2) #scale(x: 240%, y: 240%)[\(] - e^(- r^2 / 2) #scale(x: 240%, y: 240%)[\|]_0^oo #scale(x: 240%, y: 240%)[\)] d theta\
   & = integral_0^(pi\/2) 1 #h(0em) d theta = pi / 2 $

  从而得到 $I = sqrt(2 pi) / 2$. 因而
  $integral_(- oo)^oo e^(- x^2 / 2) thin d x = sqrt(2 pi)$,
  因而 $integral_(bb(R)) p\(x\)thin d x = 1$.

  从而对于任意的 $mu$ 和 $sigma$, 通过 change of variable formula
  易得 $integral_(bb(R)) p\(x\)thin d x = 1$.

- 计算其 expectation 和 variance:

  我们只需要计算 standard normal distribution 的 expectation 和 variance,
  然后通过 expectation 的 linearity 和 variance 的 scale invariance 来计算.

  令 $X tilde.op cal(N)\(0\,1\)$. Then $ bb(E)\[X\]= 1 / sqrt(2 pi) integral_(bb(R)) x e^(- x^2 / 2) #h(0em) d x = 0 $
  因为这是一个 #strong[odd function]. 从而
  $ bb(E)\[X^2\] & = 1 / sqrt(2 pi) integral_(bb(R)) x^2 e^(- x^2 / 2) #h(0em) d x = 1 / sqrt(2 pi) integral_(bb(R)) x\(x e^(- x^2 / 2)\)#h(0em) d x = 1 / sqrt(2 pi) integral_(bb(R)) x\(e^(- x^2 / 2)\)'#h(0em) d x\
   & = - 1 / sqrt(2 pi) x e^(- x^2 / 2) #scale(x: 240%, y: 240%)[\|]_(- oo)^oo + 1 / sqrt(2 pi) integral_(bb(R)) e^(- x^2 / 2) #h(0em) d x = 0 + 1 = 1 $

  从而: $ upright("Var")\(X\)= 1 $

  For general normally distributed $Y$, 我们知道了 $X : = frac(Y - mu, sigma)$ 的 $bb(E)\[X\]= 0$, $upright("Var")\(X\)= 1$, 因而 $ bb(E)\[Y\]= bb(E)\[sigma X + mu\]= mu $
  and
  $ upright("Var")\(Y\)= upright("Var")\(sigma X + mu\)= bb(E)\[\(sigma X + mu - mu\)^2\]= bb(E)\(sigma^2 X^2\)= sigma^2 bb(E)\[X^2\]= sigma^2 $

  对于多个 i.i.d. normally distributed $X$,
  $ bb(E)\[X^k\]= 1 / sqrt(2 pi) integral_(bb(R)) x^k e^(- x^2 / 2) #h(0em) d x $
  For $k$ odd, it is $0$. \ For $k$ even:
  $ bb(E)\[X^k\] & = 1 / sqrt(2 pi) integral_(bb(R)) x^(k - 1)\(x e^(- x^2 / 2)\)#h(0em) d x\
   & = - 1 / sqrt(2 pi) integral_(bb(R)) x^(k - 1)\(e^(- x^2 / 2)\)'#h(0em) d x\
   & = 0 + 1 / sqrt(2 pi) integral_(bb(R))\(x^(k - 1)\)'e^(- x^2 / 2) #h(0em) d x\
   & = frac(k - 1, sqrt(2 pi)) integral_(bb(R)) x^(k - 2) e^(- x^2 / 2) #h(0em) d x\
   & =\(k - 1\)bb(E)\[X^(k - 2)\] $
  从而: $ bb(E)\[X^k\]= {0\,quad k = 2 j - 1\
  \(2 j - 1\)\(2 j - 3\)dots.h.c 1 = frac(\(2 j\)!, 2^j j !)\,quad k = 2 j $

- 其 cdf:
  $ Phi\(a\):= F_X\(a\)= integral_(\(- oo\,a\]) rho\(x\)#h(0em) d x = 1 / sqrt(2 pi) integral_(\(- oo\,a\]) e^(- x^2 / 2) #h(0em) d x $
  我们在微积分中知道, 这个 integral 没有 closed form solution.
  因而我们只能给出数值 approximation. Important numerical values:
  $ Phi\(- 3\)approx 0.0013\;quad Phi\(- 2\)approx 0.023\;quad Phi\(- 1\)approx 0.159 $

  Note 由于 $rho$ (std) 是一个 even function, 有 $P\(X < - 1\)= P\(X > 1\)$
  因而 $ P\(X upright(" is one std dev from mean")\)= 2\(P\(X < - 1\)\)= 2 Phi\(- 1\)approx 0.32 = 32 % $
  Similarly, $ P\(X upright(" is two std dev from mean")\)approx 0.046 = 4.6 % $$ P\(X upright(" is three std dev from mean")\)approx 0.0026 = 0.26 % $

为什么 normal random variables 非常重要: 因为有一个
universality property called #strong[central limit theorem.] 之后的章节我们会展开讨论:

#heading(level: 5, numbering: none)[任意的 random variable, 只要 expectation 和 variance 都是 finite 的,
那么它们的叠加极限都会服从 normal distribution. \ ]
<任意的-random-variable-只要-expectation-和-variance-都是-finite-的-那么它们的叠加极限都会服从-normal-distribution.>
这里我们先给出一个 special case of central limit theorem:

#theorem(
  title: [DeHavre's Central limit theorem for binomial distribution],
  id: "thm-02-random-variables-dehavres-central-limit-theorem-for-binomial-distribution",
  concepts: ("dehavres-central-limit-theorem-for-binomial-distribution",),
  depends: (),
  aliases: ("DeHavre’s Central limit theorem for binomial distribution",),
)[
令 $S_n tilde.op upright("Bin")\(n\,p\)$, 则
$ lim_(n arrow.r oo) P #scale(x: 300%, y: 300%)[\(] frac(S_n - bb(E)\(S_n\), sigma\(S_n\)) in\(a\,b\)#scale(x: 300%, y: 300%)[\)] = Phi\(b\)- Phi\(a\)= 1 / sqrt(2 pi) integral_(\(a\,b\)) e^(- x^2 / 2) #h(0em) d x $

]
\(Proof: later chapters.)

#example(
  id: "ex-02-random-variables-example-012",
  concepts: ("example-012",),
  depends: (),
)[
Toss a million times 一个 fair coin. Approximate the prob that we get more than $501000$ heads:
$ bb(E)\(S_1000000\)= n p = 500000 $
$ sigma\(S_1000000\)= sqrt(n p q) = 500 $ 因而:
$ bb(P)\(S_1000000 > 501000\) & = bb(P)\(S_1000000 - bb(E)\(S_1000000\)> 1000\)\
 & = bb(P) (frac(S_1000000 - bb(E)\(S_1000000\), sigma\(S_1000000\)) > 1000 / 500)\
 & approx 1 - Phi\(2\)= Phi\(- 2\)approx 0.159 $

]
#heading(level: 5, numbering: none)[除此之外 need to mention: Poission distribution 当 $lambda arrow.r oo$ 时,
也得到 normal distribution. \ ]
<除此之外-need-to-mention-poission-distribution-当-lambda-to-infty-时-也得到-normal-distribution.>
这并不是一个令人惊讶的事情. 也可以用 central limit theorem 来解释.
因为 recall: Poisson distribution 有一个很重要的 property: additivity.
因而 $lambda arrow.r oo$ 也可以看作
$n$ 个 i.i.d. Poisson distribution 的 sum 在 $n arrow.r oo$ 时的极限行为,
从而通过 central limit theorem 得到 normal distribution.

=== summmary of discrete and continuous variables examples
<summmary-of-discrete-and-continuous-variables-examples>
#figure(
  align(center)[#table(
    columns: 6,
    align: (left,left,left,left,left,left,),
    table.header([#strong[distribution]], [#strong[pmf / pdf]], [#strong[cdf]], [#strong[$bb(E)\[X\]$]], [#strong[$upright("Var")\(X\)$]], [#strong[meaning]],),
    table.hline(),
    [$upright("Ber")\(p\)$], [$bb(P)\(X = 1\)= p$,
    $bb(P)\(X = 0\)= 1 - p$], [$F\(x\)= 1 - p\,0 lt.eq x < 1$], [$p$], [$p\(1 - p\)$], [一次 Bernoulli trial (unfair coin) 的结果],
    [$upright("Bin")\(n\,p\)$], [$bb(P)\(X = k\)= binom(n, k) p^k\(1 - p\)^(n - k)$, $k = 0\,dots.h\,n$], [$F\(k\)= sum_(j = 0)^(floor.l k floor.r) binom(n, j) p^j\(1 - p\)^(n - j)$], [$n p$], [$n p\(1 - p\)$], [$n$ 次 i.i.d. Bernoulli trials 中的成功次数],
    [$upright("Geom")\(p\)$], [$bb(P)\(X = k\)=\(1 - p\)^(k - 1)p$, $k gt.eq 1$], [$F\(k\)= 1 -\(1 - p\)^k$], [$1 / p$], [$frac(1 - p, p^2)$], [Bernoulli trial 第一次成功所需的试验次数],
    [$upright("NB")\(r\,p\)$], [$bb(P)\(X = k\)= binom(k + r - 1, k)\(1 - p\)^k p^r\,med k gt.eq 0$], [$F\(k\)= sum_(j = 0)^k binom(j + r - 1, j)\(1 - p\)^j p^r$], [$frac(r\(1 - p\), p)$], [$frac(r\(1 - p\), p^2)$], [Bernoulli trial 在 $r$ 次成功之前观察到的失败次数],
    [$upright("Poi")\(lambda\)$], [$bb(P)\(X = k\)= e^(- lambda) frac(lambda^k, k !)\,med k gt.eq 0$], [$F\(k\)= sum_(j = 0)^k e^(- lambda) frac(lambda^j, j !)$], [$lambda$], [$lambda$], [fixed window (time/space) 下某一事件的计数],
    [$U\(\[a\,b\]\)$], [$f\(x\)= frac(1, b - a)$, $a lt.eq x lt.eq b$], [$F\(x\)= cases(delim: "{", 0\, & x < a, frac(x - a, b - a)\, & a lt.eq x lt.eq b, 1\, & x > b)$], [$frac(a + b, 2)$], [$frac(\(b - a\)^2, 12)$], [uniform choice on an interval],
    [$upright("Exp")\(lambda\)$], [$f\(x\)= lambda e^(- lambda x)$, $x gt.eq 0$], [$F\(x\)= cases(delim: "{", 0\, & x lt.eq 0, 1 - e^(- lambda x)\, & x > 0)$], [$1 / lambda$], [$1 / lambda^2$], [固定平均发生率下, 某事件第一次发生要等多久],
    [$Gamma\(alpha\,lambda\)$], [$f\(x\)= frac(lambda^alpha, Gamma\(alpha\)) x^(alpha - 1) e^(- lambda x)$, $x gt.eq 0$], [$F\(x\)= frac(1, Gamma\(alpha\)) integral_0^(lambda x) t^(alpha - 1) e^(- t) thin d t$], [$alpha / lambda$], [$alpha / lambda^2$], [$alpha$ 个 i.i.d. exponential distributions 的和 (固定平均发生率下，第 $alpha$ 次事件出现前要等多久)],
    [$N\(mu\,sigma^2\)$], [$f\(x\)= 1\/sigma sqrt(2 pi) exp\(-\(x - mu\)^2\/2 sigma^2\)$], [no elementary closed form], [$mu$], [$sigma^2$], [大量微小独立扰动 (测量误差/自然波动) 叠加后的结果],
  )]
  , kind: table
  )
