#import "../../toolchain/qlnotes.typ": *
#import "../../toolchain/math-aliases.typ": *

#heading(level: 1, numbering: none)[Homework 2: on Carathéodory's and Hahn-Holmogrov Thm(40/40)]
<homework-2-on-carathéodorys-and-hahn-holmogrov-thm4040>
#emph[None of the following questions will be graded. Do them, but do not hand them in].

#heading(level: 2, numbering: none)[The Borel--Cantelli Lemma]
<the-borelcantelli-lemma>
Let $\(X\,cal(A)\,mu\)$ be a measure space. Let $A_i in cal(A)$ for $i in bb(N)$, and suppose that
$ sum_(i = 1)^oo mu\(A_i\)< oo . $
(a) Prove that $mu\(limsup_i A_i\)= 0$, where
$ limsup_i A_i = { x in X divides x in A_i upright(" for infinitely many ") i } . $
(By the way, why is $limsup_i A_i$ measurable?)

\(b) Conversely, is it true that if $A_i in cal(A)$ for $i in bb(N)$, and $mu\(limsup_i A_i\)= 0$, then $sum_i mu\(A_i\)< oo$? Provide a proof or a counterexample.
(Wrong)

#remark[
#theorem(
  title: [Borel--Cantelli Lemma],
  id: "thm-hw02-on-carath-odorys-hahn-kolmogrov-thm-borel-cantelli-lemma",
  concepts: ("borel-cantelli-lemma",),
  depends: (),
  aliases: ("Borel–Cantelli Lemma",),
)[
一个 measure 和有限的 set seq, 其 $lim sup$ (出现 infinitely many times 的元素) 是零测的.

]
其实这是 trivial 的, 因为如果出现 infinitely many times 的元素不是零测的, say $mu\(lim sup_i A_i\):= k > 0$, 那么有 infinitely many 个 $A_i$ 的测度大于等于 $k$, 那么 $sum_(i = 1)^oo mu\(A_i\)> k times oo$ 就一定不是有限的了. \ 其 application: 一个 prob space 中, a ctbl seq of 事件发生的概率的和如果收敛, 那么它们包含的任何事件发生无穷多次的概率为 0，意味着事件至多发生有限次 (almost surely).

]
#heading(level: 2, numbering: none)[The Completion of a Measure Space]
<the-completion-of-a-measure-space>
Let $\(X\,cal(A)\,mu\)$ be a measure space, and set
$ accent(cal(A), macron) := { E union F divides E in cal(A) upright(" and ") F upright(" is a ") mu upright("-subnull set") } . $

\(a) Prove that $accent(cal(A), macron)$ is a $sigma$-algebra.
(b) Define $accent(mu, macron)\(A\):= mu\(E\)$ if $A = E union F in accent(cal(A), macron)$. Prove that $accent(mu, macron)$ is a well-defined measure on $accent(cal(A), macron)$.
(c) Prove that $accent(mu, macron)$ extends $mu$ (i.e., $accent(mu, macron)\(A\)= mu\(A\)$ if $A in cal(A)$).
(d) Prove that #strong[$accent(mu, macron)$ is the unique extension of $mu$ to $\(X\,accent(cal(A), macron)\)$]. In other words, prove that if $mu'$ is another measure on $\(X\,accent(cal(A), macron)\)$ that extends $mu$, then $mu' = accent(mu, macron)$.
(e) Prove that #strong[$accent(mu, macron)$ is complete].
(f) Suppose $\(X\,cal(A)'\,mu'\)$ is another complete measure space that extends $\(X\,cal(A)\,mu\)$ (i.e., $cal(A) subset cal(A)'$ and $mu'\|_(cal(A))= mu$). Show that #strong[$accent(cal(A), macron) subset cal(A)'$ and $mu'\|_(accent(cal(A), macron))= accent(mu, macron)$.]
#strong[Hint:] Start by reading Theorem 1.9 in Folland.

#proof[
略.(嘻嘻)

]
#heading(level: 2, numbering: none)[The Hahn--Kolmogorov Extension as a Completion]
<the-hahnkolmogorov-extension-as-a-completion>
Let $\(X\,cal(A)_0\,mu_0\)$ be a $sigma$-finite measure pre-measure space, and $\(X\,cal(A)\,mu\)$ its Hahn--Kolmogorov extension. Prove that $\(X\,cal(A)\,mu\)$ is the completion of its restriction to the $sigma$-algebra $chevron.l cal(A)_0 chevron.r$ generated by $cal(A)_0$.

#proof[
Proved in lec notes.

]
#emph[Some of the following questions will be graded. Do them, and do hand them in].

#heading(level: 2, numbering: none)[$mu\(nothing\)= 0$ 的定义并非 redundant]
<muemptyset-0-的定义并非-redundant>
Let $\(X\,cal(A)\)$ be a measurable space. Is the condition $mu\(nothing\)= 0$ in the definition of a measure on $\(X\,cal(A)\)$ redundant? In other words, if $mu : cal(A) arrow.r\[0\,oo\]$ is a function such that
$ mu (union.big_(i = 1)^oo A_i) = sum_(i = 1)^oo mu\(A_i\)\, $
for any disjoint subsets $A_i in cal(A)$, $i in bb(N)$, does it follow that $mu\(nothing\)= 0$? If not, what can you say?

#proof[
It does not follow. \ Counterexample: Consider $mu\(E\)= oo #h(0em) #h(0em) forall E in cal(A)$. \ This measure satisfies the countably disjoint additivity condition, since for every disjoint sequence of sets in $cal(A)$, $mu (union.big_(i = 1)^oo A_i) = sum_(i = 1)^oo mu\(A_i\)= oo$ has infinite measure.

]
#heading(level: 2, numbering: none)[measurable set seq 的 limit 也 measurable (且如果 seq tail $sigma$-finite $arrow.r.double.long$ limit commute )]
<measurable-set-seq-的-limit-也-measurable-且如果-seq-tail-sigma-finite-implies-limit-commute>
Let $\(X\,cal(A)\,mu\)$ be a measure space, and let $A_i in cal(A)\,i in bb(N)$. Assume that the sets $A_i$ converge to the set $A subset X$ in the sense that:
\- If $x in A$, then $x in A_i$ for all but finitely many $i$\;
\- If $x in.not A$, then $x in.not A_i$ for all but finitely many $i$.

#strong[\(a) Prove that $A$ is measurable, that is, $A in cal(A)$.]

#proof[
Deduing from the conditions:
If $x in A$, then $x in A_i$ for all but finitely many $i$\; $arrow.r.double.long$ $A subset liminf A_i$
If $x in.not A$, then $x in.not A_i$ for all but finitely many $i$. $arrow.r.double.long$ if $x in A_i$ for all but finitely many $i$ then $x in A$ $arrow.r.double.long$ $limsup A_i subset A$
Thus
$ limsup A_i subset A subset liminf A_i $

#strong[Claim1: For any sequence of sets $\(A_i\)_(i in bb(N))$, we have
$ liminf A_i subset limsup A_i $]
Proof of Claim 1: Follows trivially from the definition, since $x in.not A_i$ for all but finitely many $i$ $arrow.r.double.long$ $x in.not A_i$ for infinitely many $i$. \ \ Combining claim (1) with (2.1) we have
$ limsup A_i = A = liminf A_i $
#strong[Claim 2: For any sequence of sets $\(A_i\)_(i in bb(N))$ in a $sigma$-algebra, $liminf_i A i$ and $limsup_i A_i$ is also in the $sigma$-algebra.] \ Proof of Claim 2: This follows from the def and fact that union and intersection of a countable sequence sets in a $sigma$-algebra is also in this $sigma$-algebra. We have

#figure(image("../assets/hw2(1).jpeg", width: 80.0%),
  caption: [
  ]
)

This finishes the proof of Claim 2. \ Combining claim 2 with (2.2), $A in cal(A)$, this finishes the proof. \

]
#strong[\(b) Prove that if there exists $n gt.eq 1$ such that $mu (union.big_(i = n)^oo A_i) < oo$, then $mu\(A\)= lim_i mu\(A_i\)$.]

#proof[

#figure(image("../assets/hw2(2).png", width: 70.0%),
  caption: [
  ]
)

#figure(image("../assets/hw2(3).png", width: 70.0%),
  caption: [
  ]
)

]
#strong[\(c) Give an example showing that the condition in (b) is necessary].

#solution[
Let $mu$ be the Lebesgue measure defined on $cal(B)\(bb(R)\)$. We set for each $i in bb(N)$ that
$ A_i =\(i\,i + 1\) $
Since this is an interval, it is Lebesgue measurable. Note that no element of any $A_i$ show up infinitely many times in the sequence. So
$ liminf A_i = limsup A_i = diameter $
So $A = diameter$, we have $lim_i mu\(A_i\)= 0$.
But we have $lim_i mu\(A_i\)= 1$ since it is true for every $i$. \ In this case, $mu\(union.big_(i = 1)^oo A_i\)= oo$, which causes (b) to fail.

]
#strong[Hint:] In analysis, it is often fruitful to use $limsup$ and $liminf$ to study limits. \

#heading(level: 2, numbering: none)[measure space of two elements]
<measure-space-of-two-elements>
Let $X$ be a set with two elements, for example, $X = { O\,Q }$. \ #strong[\(a) Find all $sigma$-algebras on $X$.]

#solution[
+ trivial $sigma$-algebra:$ cal(A)_1 := { diameter\,#h(0em) X } $

+ power set:
  $ cal(A)_2 := cal(P)\(X\)#h(0em) = #h(0em) { diameter\,#h(0em) { O }\,#h(0em) { Q }\,#h(0em) X } $

These are the only $sigma$-algebras on $X$. \ \

]
#strong[\(b) Let $cal(A)$ be a $sigma$-algebra on $X$, and $mu$ a measure on $\(X\,cal(A)\)$. Is $mu$ necessarily complete? Provide a proof or a counterexample.]

#solution[
It is not necessarily complete. \ Cosider the trivial $sigma$-algebra:$cal(A)_1 := { diameter\,#h(0em) X }$, and set $mu$ as that $mu\(diameter\)= mu\(X\)= 0$. This makes $X$ a null set, so ${ O }\,{ Q }$ are subnull sets, but they are not measurable by $mu$. \ \

]
#strong[\(c) Find all outer measures $mu^(*)$ on $X$. For each outer measure on $X$, find the $sigma$-algebra of $mu^(*)$-measurable sets (see Carathéodory's theorem).]

#solution[
Suppose $mu^(*)$ is an outer measure on $X$. Since $cal(P)\(X\)$ only has four elements: $diameter$, ${ O }$, ${ Q }$, $X$\; and the outer measure of $diameter$ is 0, so we first parametrize $mu^(*)$ by:
$ a := mu^(*)\({ O }\)\,quad b := mu^(*)\({ Q }\)\,quad c := mu^(*)\(X\). $

]
Then $mu^(*)$ is well-defined iff it satisfies:

+ $a\,b lt.eq c$

+ $c = mu^(*)\({ O } union { Q }\)#h(0em) lt.eq #h(0em) mu^(*)\({ O }\)+ mu^(*)\({ Q }\)#h(0em) = #h(0em) a + b .$

Any $\(a\,b\,c\)in\[0\,oo\]^3$ satisfying
$ max\(a\,b\)#h(0em) lt.eq #h(0em) c #h(0em) lt.eq #h(0em) a + b\, $
can make $mu^(*)$ a well-defined outer measure on $X$. \ Therefore
$ S := { upright("all ") sigma upright("-algebra on ") X } = { mu^(*) : cal(P)\(X\)arrow.r\[0\,oo\]divides max\(mu^(*)\({ O }\)\,mu^(*)\({ Q }\)\)lt.eq mu^(*)\(X\)lt.eq mu^(*)\({ O }\)+ mu^(*)\({ Q }\)} $ \ Now we specify the $sigma$-algebra of $mu^(*)$-measurable sets for each $mu^(*) in S$. \ By Carathéodory's criterion, a set $E subset X$ is $mu^(*)$-measurable iff for all $A subset X$,
$ mu^(*)\(A\)#h(0em) = #h(0em) mu^(*)\(A inter E\)#h(0em) + #h(0em) mu^(*)\(A inter E^c\). $
Note that $diameter$, $X$ are always measurable since for any $A subset X$, $A inter diameter = diameter\,#h(0em) A inter\(diameter\)^c= A$\; and $A inter X = A\,#h(0em) A inter\(X\)^c= diameter$. So it suffices to check for ${ O }\,{ Q }$. We first check for ${ O }$. ${ O }$ is $mu^(*)$-measurable iff $mu^(*)\(A\)#h(0em) = #h(0em) mu^(*)\(A inter { O }\)#h(0em) + #h(0em) mu^(*)\(A inter { O }^c\)$ for any choice of $A$.
There are only four possibilities for $A$: $diameter$, ${ O }$, ${ Q }$, $X$.

+ If $A = diameter$, both sides are 0, always stands.

+ If $A = { O }$, then $mu^(*)\({ O }\)+ mu^(*)\(diameter\)= a + 0 = a$, always stands.

+ If $A = { Q }$, then $mu^(*)\(diameter\)+ mu^(*)\({ Q }\)= 0 + b = b$, always stands.

+ If $A = X$, then $mu^(*)\(X\)= c = mu^(*)\({ O }\)+ mu^(*)\({ Q }\)= a + b$.

Therefore ${ O }$ is $mu^(*)$-measurable iff $c = a + b$. For the same reasoning, ${ Q }$ is $mu^(*)$-measurable iff $c = a + b$. \ Thus we can conclude that:

+ If $c = a + b$, ${ mu^(*) upright("-measurable sets") } = cal(P)\(X\)$.

+ otherwise, ${ mu^(*) upright("-measurable sets") } = { diameter\,X }$.

#strong[\(d) Find an example of a collection $cal(E)$ of subsets of $X$ with $nothing\,X in cal(E)$ and a function $rho : cal(E) arrow.r\[0\,oo\]$ with $rho\(nothing\)= 0$ such that $cal(E) subset.not cal(A)$, where $cal(A)$ is the Carathéodory $sigma$-algebra for the outer measure $mu^(*)$ induced by $\(cal(E)\,rho\)$.]

#solution[
Consider $cal(E) = { diameter\,X\,{ O } }$, with $rho$ such that $rho\(nothing\)= 0$, $rho\(X\)= 1$, $rho\({ O }\)= 1$. \ The outer measure $mu^(*)$ induced by $mu^(*)$ is: $mu^(*)\(X\)= 1$, $mu^(*)\({ O }\)= 1$, $mu^(*)\({ Q }\)= 1$. (the inf of length sum of sets covering ${ Q }$ is 1, by taking ${ X }$ as the covering.) \ Since $c eq.not a + b$, by (4), the Carathéodory $sigma$-algebra by $mu^(*)$ by $cal(E)$ is ${ diameter\,X }$, so $cal(E) subset.not cal(A)$. \ \

]
#strong[Remark:] The Hahn--Kolmogorov theorem states that if $cal(E) = cal(A)_0$ is an algebra and $rho = mu_0$ is a pre-measure, then $cal(A)_0 subset cal(A)$. This exercise provides a counterexample when $cal(E)$ and $rho$ are general.
、

#heading(level: 2, numbering: none)[Hahn--Kolmogorov Collapse (when $mu_0$ not $sigma$-finite)]
<hahnkolmogorov-collapse-when-mu_0-not-sigma-finite>
Let $X subset bb(R)$ be the set of dyadic rational numbers, that is, the set of numbers of the form $r / 2^n$, where $r$ and $n$ are integers. Let $cal(A)_0 subset cal(P)\(X\)$ be the collection of finite unions of intervals of the form $\(a\,b\]inter X$, where $- oo lt.eq a < b lt.eq oo$.

#strong[\(a) Prove that $cal(A)_0$ is an algebra.]

#proof[

+ $diameter in cal(A)_0$, since it is the empty union of intervals of the given form.

+ #strong[Closed under complements]: Let $A in cal(A)_0$. Then $A$ is a finite union of intervals of the form $\(a_i\,b_i\]inter X$. So $ A^c inter X & = X\\A\
   & = X\\ union.big_(i = 1)^n \(\(a_i\,b_i\]inter X \) \)\
   & = X inter \( inter.big_(i = 1)^n \(\(a_i\,b_i\]inter X \)^c \)\
   & = X inter \( inter.big_(i = 1)^n \(\(- oo\,a_i\]union\(b_i\,oo\]\) \) $
  Note that finite intersection of intervals of the form $\(- oo\,a_i\]$, $\(b_i\,oo\]$ is still of this form. Hence $A^c inter X in cal(A)_0$.

+ #strong[Closed under finite unions]: Suppose $A_1$ and $A_2$ are finite unions of intervals $\(\(a_i\,b_i\]inter X \)$, then $A_1 union A_2$ is still a finite union of intervals of that form. (They either merge into one such interval, so are disjoint.) Hence $A_1 union A_2 in cal(A)_0$. The same reasoning extends to any finite union.

#strong[This finishes the proof that $cal(A)_0$ is an algebra on $X$.] \ \

]
#strong[\(b) Prove that the $sigma$-algebra on $X$ generated by $cal(A)_0$ equals $cal(P)\(X\)$.]

#proof[
Since $< cal(A)_0 > subset cal(P)\(X\)$, it suffices to show that $cal(P)\(X\)subset < cal(A)_0 >$.
Note that $X$ is countable, so any set in $cal(P)\(X\)$ is a countable union of singleton sets. Thus it suffices to show that any singleton set ${ x }$ where $x in X$ is in $< cal(A)_0 >$, since if so, then any countable union of singleton sets from $cal(P)\(X\)$ is also in $< cal(A)_0 >$, with implies that $cal(P)\(X\)subset < cal(A)_0 >$ \ Let $x in X$. Then we have:
$ { x } #h(0em) = #h(0em) inter.big_(n = 1)^oo \(\(x - 1 / 2^n\,thin x\]inter X \)\, $
since $x$ is in the RHS set, and for any $y < x$, we can find a $n in cal(B)$ such that $x - 1 / 2^n > y$. \ This finishes the proof that $< cal(A)_0 > = cal(P)\(X\)$.

]
#strong[\(c) Define $mu_0 : cal(A)_0 arrow.r\[0\,oo\]$ by $mu_0\(nothing\)= 0$ and $mu_0\(A\)= oo$ for $A eq.not nothing$. Prove that $mu_0$ is a pre-measure on $cal(A)_0$]

#proof[
It suffices to show the countable disjoint additivity. \ Let $\(A_i\)_(i in cal(N))$ be a sequence of disjoint sets in $cal(A)_0$. \ Case 1: all $A_i = diameter$, then $union.sq_(i in cal(N)) A_i = diameter$, so $mu_0\(union.sq_(i in cal(N)) A_i\)= sum_(i in cal(N)) mu_0\(A_i\)= 0$. \ Case 2: $A_k eq.not diameter$ for some $k$, then $mu_0\(A_k\)= oo$ and $union.sq_(i in cal(N)) A_i eq.not diameter$. Thus $sum_(i in cal(N)) mu_0\(A_i\)gt.eq mu_0\(A_k\)= oo = mu_0\(union.sq_(i in cal(N)) A_i\)$. \ The two cases cover all circumstances, finishing the proof. \

]
#strong[\(d) Prove that there exist infinitely many different measures $mu$ on $cal(P)\(X\)$ whose restriction to $cal(A)_0$ equals $mu_0$.]

#proof[
Given $n in bb(N)$, We define the \"n-timed counting measure\" on a $sigma$-algebra $S$ as:
$ mu_(c o u n t_n)\(E\):= {n times\#\(E\)#h(0em) #h(0em)\,upright(" if ") E upright(" is finite ")\
oo #h(0em) #h(0em)\,upright(" if ") E upright(" is infinite ") $

#strong[Claim 1: For any set $X$ and any $sigma$-algebra $S$ on $X$, the \"n-timed counting measure\" is a well-defined measure on $S$, for all $n in bb(N)$.] \ Proof of claim 1: $mu_(c o u n t_n)\(diameter\)= 0$ since $"card"\(diameter\)= 0$, and countable disjoint additivity trivially follows from the rule of counting. \ #strong[Claim 2: for any $n in bb(N)$, $mu_(c o u n t_n)\(E\)$ on $cal(P)\(X\)$ restricted to $cal(A)_0$ equals $mu_0$.]
Proof of claim 2: Let $E in cal(A)_0\\diameter$, then $E$ contains at least one interval of the form $\(a\,b\]inter X$, where $- oo lt.eq a < b lt.eq oo$. Sicne $a < b$, there are infinitely many elements in $\(a\,b\]inter X$, so $mu_(c o u n t_n)\(E\)= oo$. \ This finishes the proof of the original statement. \

]
#strong[\(e) Explain why (d) does not contradict the uniqueness part of the Hahn--Kolmogorov theorem (see Theorem 1.14 in Folland).] \

#solution[
This is because Hahn--Kolmogorov theorem requires $mu_0$ to be $sigma$-finite to extend uniquely on $< cal(A)_0 >$. But $mu_0$ here is not $sigma$-finite. \

]
#heading(level: 2, numbering: none)[Nur für Verrückte (Only for nuts)]
<nur-für-verrückte-only-for-nuts>
\(It's really not necessary to attempt these problems. Do not, under any circumstances, hand them in!)

\1. Let $\(X\,cal(A)\,mu\)$ and $\(Y\,cal(B)\,nu\)$ be measure spaces. Define a morphism from $\(X\,cal(A)\,mu\)$ to $\(Y\,cal(B)\,nu\)$ to be a map $f : X arrow.r Y$ that is measurable, that is, $f^(- 1)\(B\)in cal(A)$ for all $B in cal(B)$, and moreover measure preserving, in the sense that $mu\(f^(- 1)\(B\)\)= nu\(B\)$ for all $B in cal(B)$.

\(a) Prove that measure spaces with measure-preserving maps as morphisms form a category. Denote this category by $C_3$.

\(b) Denote by $C_1$ the category of sets, and by $C_2$ the category of measurable spaces (see HW1). Consider the evident forgetful functors $C_3 arrow.r C_2$ and $C_2 arrow.r C_1$. Are these functors faithful? Are they full? Are they essentially surjective?
