site_name: Advanced Linear Algebra
site_author: qiulinfan
site_url: https://qiulinfan.github.io/
use_directory_urls: false
remote_branch: gh-deploy

repo_name: qlblog
repo_url: https://github.com/qiulinfan/qiulinfan.github.io

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Chapters:
    - 01-review-on-basic-concepts: 01-review-on-basic-concepts.md
    - 02-linear-functionals-and-duality: 02-linear-functionals-and-duality.md
    - 03-eigenvalues-and-operators: 03-eigenvalues-and-operators.md
    - 04-operators-on-complex-vector-spaces: 04-operators-on-complex-vector-spaces.md
    - 05-multilinear-algebra: 05-multilinear-algebra.md
