#import "../../toolchain/qlnotes.typ": *
#import "../../toolchain/math-aliases.typ": *

#let bF = math.bb("F")

= tensor product and matrix multiplication

这里我们放弃陈述两个 over 同一 field 的 vector spaces 的 tensor product 的 algebraic definition，直接看应用的。(完整的 definition 是两个 over 同一个 ring 的 modules $A, B$，取它们 free abelian group generated by $A times B$，再 quotient 掉一个用来形成 bilinearity 的 subgroup，就是它们的 tensor product。当这两个东西是 vector spaces 时，它们并且是 isomorphic to 其对应的 bilinear functional vector space的。)

#definition(title: [(not rigorous) #kn[Tensor product]])[
令 $V, W$ be vector spaces over $bF$，我们定义一个 vector 与 vector 之间的 tensor product operation：

$⊗ : (v, w) arrow.r v ⊗ w$

s.t. 对于 $V, W$ 的 basis $e_1, dots, e_n$ 和 $epsilon_1, dots, epsilon_m$，我们给每个 $(e_i, epsilon_j)$ 都赋予一个不同的 image $e_i ⊗ epsilon_j$，其 over $bF$ 具有 bilinear 性。

对于

$V ⊗ W := "span"({e_i ⊗ e_j : 1 <= i <= n, 1 <= j <= m})$

$V ⊗ W$ 也是一个 over $bF$ 的 vector space，且 $"dim"(V ⊗ W) = m n$。
]

#proposition(title: [representing tensor product as matrix])[
如果我们有两个矩阵：

$A = mat(a_11, a_12; a_21, a_22), quad B = mat(b_11, b_12; b_21, b_22)$

可以把它们的 tensor product $A ⊗ B$ 表示为：

$A ⊗ B = mat(a_11 B, a_12 B; a_21 B, a_22 B) = mat(
  a_11 b_11, a_11 b_12, a_12 b_11, a_12 b_12;
  a_11 b_21, a_11 b_22, a_12 b_21, a_12 b_22;
  a_21 b_11, a_21 b_12, a_22 b_21, a_22 b_22;
  a_21 b_21, a_21 b_22, a_22 b_21, a_22 b_22
)$

can verify：这个表示是符合 tensor product 的 bilinearity 的。

(我们可以把 $A$，$B$ 分别看作 $m times n$，$p times q$ dim 的向量，这个 $A ⊗ B$ 是 $m times n times p times q$ dim 的向量。)
]

#definition(title: [outer product of two vectors])[
对于 $v in bF^n$，$w in bF^m$，我们定义它们的 outer product $v ⊗ w$为：

$v w := v ⊗ w^T = mat(v_1; dots; v_n) ⊗ mat(w_1, dots, w_m) = mat(v_1 w^T; dots; v_n w^T) = mat(w_1 v, dots, w_m)$
]

== matrix product through outer product

#theorem(title: [representing matrix multiplication by outer products])[
对于 $m times n$ 的矩阵 $A$ 和 $n times k$ 的矩阵 $B$，we have：

$A B = sum_(i=1)^n A_(*i) ⊗ B_(i*)$
]

#proof[In md.]

#remark[
两个 vectors 的 outer product，一*定是一个 rank 为 1 的 matrix*。因为它每一 column 都是 $v$ 的一个倍数。

但是我们可以累加 $n$ 个这样的 outer products，从而得到一个可以是 full rank $n$ 的矩阵。(我们知道当然，矩阵相加不保留 rank。)
]
