site_name: Multivariate Analysis
site_author: qiulinfan
site_url: https://qiulinfan.github.io/
use_directory_urls: false
remote_branch: gh-deploy

repo_name: qlblog
repo_url: https://github.com/qiulinfan/qiulinfan.github.io

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Chapters:
    - 01-topology-in-rn: 01-topology-in-rn.md
    - 02-differentiation: 02-differentiation.md
    - 03-integration: 03-integration.md
    - 04-change-of-variables: 04-change-of-variables.md
    - 05-multilinear-algebra: 05-multilinear-algebra.md
