#!/bin/sh

# Generate each runtime's installed global guidance file from the shared core
# and that runtime's delta. The generated files are committed so every linker
# can install them as a plain link, and so a fresh checkout is usable without
# running this script.
#
#   install/agents/build-guidance.sh           # write the generated files
#   install/agents/build-guidance.sh --check    # fail if they are stale

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
install_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
repo_root=$(CDPATH= cd -- "$install_root/.." && pwd)
core_source="$script_dir/core.md"

check_only=false
case "${1:-}" in
  --check) check_only=true ;;
  '') ;;
  *)
    printf 'usage: %s [--check]\n' "$0" >&2
    exit 2
    ;;
esac

[ -f "$core_source" ] || {
  printf 'missing shared core: %s\n' "$core_source" >&2
  exit 1
}

runtime_source_path() {
  printf '%s/%s/runtime.md' "$install_root" "$1"
}

emit_runtime() {
  runtime_dir=$1
  printf '<!-- Generated by install/agents/build-guidance.sh. Do not edit. -->\n'
  printf '<!-- Sources: install/agents/core.md + install/%s/runtime.md -->\n' "$runtime_dir"
  printf '<!-- Regenerate with: make agents-guidance -->\n\n'
  cat "$core_source"
  printf '\n'
  cat "$(runtime_source_path "$runtime_dir")"
}

render_runtime() {
  runtime_dir=$1
  generated_path="$install_root/$runtime_dir/$2"
  runtime_source=$(runtime_source_path "$runtime_dir")
  relative_generated=${generated_path#"$repo_root"/}

  [ -f "$runtime_source" ] || {
    printf 'missing runtime guidance: %s\n' "$runtime_source" >&2
    exit 1
  }

  if [ "$check_only" = true ]; then
    if [ -f "$generated_path" ] && emit_runtime "$runtime_dir" | cmp -s - "$generated_path"; then
      printf 'ok: %s is current\n' "$relative_generated"
      return
    fi
    printf 'stale generated guidance: %s (run: make agents-guidance)\n' "$relative_generated" >&2
    exit 1
  fi

  emit_runtime "$runtime_dir" > "$generated_path.tmp.$$"
  mv "$generated_path.tmp.$$" "$generated_path"
  printf 'ok: wrote %s\n' "$relative_generated"
}

render_runtime codex AGENTS.md
render_runtime claude CLAUDE.md
